package com.binjiang.http;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.security.KeyManagementException;
import java.security.NoSuchAlgorithmException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.net.ssl.HostnameVerifier;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSession;

import org.apache.http.HttpHost;
import org.apache.http.HttpResponse;
import org.apache.http.HttpStatus;
import org.apache.http.NameValuePair;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.config.RequestConfig;
import org.apache.http.client.entity.UrlEncodedFormEntity;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpGet;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.methods.HttpUriRequest;
import org.apache.http.client.utils.URLEncodedUtils;
import org.apache.http.conn.ssl.SSLConnectionSocketFactory;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.impl.client.HttpClients;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.protocol.BasicHttpContext;
import org.apache.http.protocol.HttpContext;
import org.apache.http.protocol.HttpCoreContext;
import org.apache.http.ssl.SSLContexts;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.select.Elements;

/**
 * @author javebean 
 */	
public class CallRemote {

	private static final  String BASEURL= "http://sql.bjxy.cn/";
	
	private static CloseableHttpClient httpclient = null;
	
	/**
	 * 设置请求参数
	 * @param param
	 * @return
	 */
	private static List<NameValuePair> setParamMap(Map<String,String> param){
		List<NameValuePair> nvps = new ArrayList<NameValuePair>();
		for (Map.Entry<String, String> map : param.entrySet()) {
			nvps.add(new BasicNameValuePair(map.getKey(), map.getValue()));
		}
		return nvps;
	}
	
	
	/**
	 * 设置超时
	 * @return
	 */
	private static RequestConfig setRequestConfig(){
		/* 设置超时 */
		RequestConfig requestConfig = RequestConfig.custom()
				.setConnectionRequestTimeout(10000).setConnectTimeout(10000)
				.setSocketTimeout(10000).build();
		return requestConfig;
	}
	
	
	/**
	 * get请求
	 * @param interfaceName
	 * @param param
	 * @param httpclient
	 * @return
	 */
	public static String httpGetFunc(String interfaceName, Map<String,String> param){
		try {
			HttpGet httpGet = null;
			if(null==param){
				httpGet = new HttpGet(interfaceName);
			}else{
				String paramString = URLEncodedUtils.format(setParamMap(param), "utf-8");
				httpGet = new HttpGet(interfaceName + "?" + paramString);
			}
			//httpGet.setConfig(setRequestConfig());
			 CloseableHttpResponse execute = httpclient.execute(httpGet);
			 
			 return getOutResultString(execute);
		} catch (ClientProtocolException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
			return null;
	}
	
	/**
	 * post请求
	 * @param interfaceName
	 * @param param
	 * @param httpclient
	 * @return
	 */
	public static String httpPostFunc(String interfaceName, Map<String,String> param){
		HttpPost httpPost = new HttpPost(interfaceName);
		try {
			httpPost.setEntity(new UrlEncodedFormEntity(setParamMap(param), "UTF-8"));
			CloseableHttpResponse chr =  httpclient.execute(httpPost);
			return getOutResultString(chr);
		} catch (ClientProtocolException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		}
		return null;
	}
	
	/**
	 * 初始化httpClient
	 * @return
	 */
	static{
		SSLContext sslContext = null;
		try {
			sslContext = SSLContexts.custom().build();
		} catch (KeyManagementException e) {
			e.printStackTrace();
		} catch (NoSuchAlgorithmException e) {
			e.printStackTrace();
		}
		SSLConnectionSocketFactory sf = new SSLConnectionSocketFactory(
				sslContext, new String[] { "TLSv1", "TLSv1.1", "TLSv1.2" },
				null, new HostnameVerifier() {
					@Override
					public boolean verify(String hostname, SSLSession session) {
						return true;
					}

				});
		httpclient = HttpClients.custom().setSSLSocketFactory(sf).build();
	}
	
	/**
	 * 得到输出结果
	 * @param response
	 * @return
	 */
	public static String getOutResultString(CloseableHttpResponse response){
		StringBuilder out = new StringBuilder();
		try{
			InputStream body2 = response.getEntity().getContent();
			BufferedReader reader = new BufferedReader(new InputStreamReader(body2,
					"UTF-8"));
			String line;
			while ((line = reader.readLine()) != null) {
				out.append(line);
			}
		}catch(IOException e){
			e.printStackTrace();
		}
		return out.toString();
	}
	
	/**
	 * 得到登陆参数
	 * @return
	 */
	public static Map<String,String> getLogin_param(){
		Map<String,String> param = new HashMap<String, String>();
		String __VIEWSTATE = "/wEPDwUKMTM5MjUxOTk4Nw9kFgJmD2QWHgICDxAPFgIeB1Zpc2libGVoZGQWAWZkAgMPEA8WAh8AaGRkZGQCBA8QDxYCHwBoZGRkZAIFDxAPFgIeBFRleHQFCeaVmeWKoeWKnmRkZGQCBg8QDxYCHwBoZGRkZAIHDxAPFgIfAQUG5a2m6ZmiZGRkZAIIDxAPFgIfAQUG5a2m5YqeZGRkZAIJDxAPFgIfAQUJ54+t5Li75Lu7ZGRkZAIKDxAPFgIfAQUG5pWZ5biIZGRkZAILDxAPFgIfAQUG5a2m55SfZGRkZAIMDxAPFgIfAGhkZGRkAg0PEA8WAh8AaGRkZGQCDg8QDxYCHwBoZGRkZAIPDxAPFgIfAGhkZGRkAhAPEA8WAh8AaGRkZGQYAQUeX19Db250cm9sc1JlcXVpcmVQb3N0QmFja0tleV9fFgsFDFJhZGlvQnV0dG9uNAUMUmFkaW9CdXR0b240BQxSYWRpb0J1dHRvbjIFDFJhZGlvQnV0dG9uMgUMUmFkaW9CdXR0b241BQxSYWRpb0J1dHRvbjUFDFJhZGlvQnV0dG9uNgUMUmFkaW9CdXR0b242BQxSYWRpb0J1dHRvbjEFDFJhZGlvQnV0dG9uMQUMUmFkaW9CdXR0b24zgSA0j9U6LMstXJZ0msYa1SCi3L4=";
		param.put("__VIEWSTATE", __VIEWSTATE);
		/*param.put("TextBox1", "20122344003");
		param.put("TextBox2", "888888");
		param.put("js", "RadioButton3");*/
		param.put("Button1", "登陆");
		param.put("Button2", "重填");
		return param;
	}
	
	
	
	public static void main(String[] args) throws IOException {
		
		//获取redirect后的动态url
		String currentUrl = getRedirectUrl();
	
		//登陆
		String result = httpGetFunc(currentUrl, getLogin_param());
		System.out.println(result);
		
		//截取掉default.aspx
		currentUrl = currentUrl.substring(0, currentUrl.lastIndexOf("/")+1);
		
		
		//登陆成功,跳转到课表页面
		String kb = httpGetFunc(currentUrl+"public/kebiaoall.aspx", null);
		
		//解析课表页面
		Map<String,String> kbMap = new HashMap<String, String>();
		Document loginHtml = Jsoup.parse(kb);
		Elements __VIEWSTATE = loginHtml.select("input[name=__VIEWSTATE]");
		Elements __EVENTVALIDATION = loginHtml.select("input[name=__EVENTVALIDATION]");

		kbMap.put("__VIEWSTATE", __VIEWSTATE.val());
		kbMap.put("__EVENTVALIDATION", __EVENTVALIDATION.val());
		
		kbMap.put("StudentJZ1$DropDownListXY", "52");
		/*kbMap.put("StudentJZ1$DropDownListZYMC", "2344");
		kbMap.put("StudentJZ1$DropDownListDQSZJ", "2012");
		kbMap.put("StudentJZ1$DropDownListXZB", "12软件1");
		kbMap.put("XN1$DropDownListXN", "2013-2014");
		kbMap.put("XQ1$DropDownListXQ", "1");*/
		kbMap.put("__EVENTTARGET", "StudentJZ1$DropDownListXY");
		kbMap.put("__EVENTARGUMENT", "");
		kbMap.put("__LASTFOCUS", "");
		
		//获得课表
		String kbResponse = httpPostFunc(currentUrl+"public/kebiaoall.aspx", kbMap);
		
	}


	
	
	
	
	
	
	/**
	 * 获取redirect后的动态url
	 * @param httpclient
	 * @return
	 * @throws IOException
	 * @throws ClientProtocolException
	 */
	public static String getRedirectUrl()
			throws IOException, ClientProtocolException {
		HttpGet httpget = new HttpGet(BASEURL);
        HttpContext context = new BasicHttpContext(); 
        HttpResponse response = httpclient.execute(httpget, context); 
        if (response.getStatusLine().getStatusCode() != HttpStatus.SC_OK)
            throw new IOException(response.getStatusLine().toString());
		HttpUriRequest currentReq = (HttpUriRequest) context.getAttribute( 
                HttpCoreContext.HTTP_REQUEST);
        HttpHost currentHost = (HttpHost)  context.getAttribute( 
        		HttpCoreContext.HTTP_TARGET_HOST);
        String currentUrl = (currentReq.getURI().isAbsolute()) ? currentReq.getURI().toString() : (currentHost.toURI() + currentReq.getURI());
		return currentUrl;
	}
	
	
	
	
	private static CloseableHttpResponse selectClasskb(){
		Map<String,String> academe = new HashMap<String, String>();
		academe.put("大气科学学院","01");
		academe.put("环境科学与工程学院","02");
		academe.put("教务处","0");
		academe.put("电子与信息工程学院","03");
		academe.put("语言文化学院","04");
		academe.put("数理学院","05");
		academe.put("信息与控制学院","06");
		academe.put("计算机与软件学院","07");
		academe.put("体育部","08");
		academe.put("经济管理学院","09");
		academe.put("应用气象学院","10");
		academe.put("公共管理学院","11");
		academe.put("遥感学院","13");
		academe.put("传媒与艺术学院","14");
		academe.put("图书馆","15");
		academe.put("成人教育学院","17");
		academe.put("大气物理学院","18");
		academe.put("滨江学院","19");
		academe.put("物理与光电工程学院","20");
		academe.put("地理与遥感学院","21");
		academe.put("环境科学与工程学院","22");
		academe.put("数学与统计学院","23");
		academe.put("团委","25");
		academe.put("学生工作处","26");
		academe.put("审计处","27");
		academe.put("滨江学院理学系","51");
		academe.put("滨江学院计算机系","52");
		academe.put("滨江学院经济与贸易系","53");
		academe.put("滨江学院外语系","54");
		academe.put("滨江学院公共管理系","55");
		academe.put("滨江学院会计系","56");
		academe.put("滨江学院电子工程系","57");
		academe.put("滨江学院大气与遥感系","58");
		academe.put("滨江学院自动控制系","59");
		academe.put("人武部","80");
		academe.put("大学英语部","81");
		academe.put("思想政治理论课教育中心","82");
		academe.put("滨江学院花旗营校区","99");
		
		
		Map<String,String> map = new HashMap<String, String>();
		map.put("__EVENTTARGET", "");
		map.put("__EVENTARGUMENT", "");
		map.put("__LASTFOCUS", "");
		map.put("__VIEWSTATE", "/wEPDwUKLTI5NDgyMTg1Nw9kFgICAQ9kFggCAw9kFgICAQ9kFgJmD2QWCAIBDxAPFgIeDERhdGFTb3VyY2VJRGRkEBUnCeaVmeWKoeWkhBLlpKfmsJTnp5HlrablrabpmaIb546v5aKD56eR5a2m5LiO5bel56iL5a2m6ZmiG+eUteWtkOS4juS/oeaBr+W3peeoi+WtpumZohLor63oqIDmlofljJblrabpmaIM5pWw55CG5a2m6ZmiFeS/oeaBr+S4juaOp+WItuWtpumZohjorqHnrpfmnLrkuI7ova/ku7blrabpmaIJ5L2T6IKy6YOoEue7j+a1jueuoeeQhuWtpumZohLlupTnlKjmsJTosaHlrabpmaIS5YWs5YWx566h55CG5a2m6ZmiDOmBpeaEn+WtpumZohXkvKDlqpLkuI7oibrmnK/lrabpmaIJ5Zu+5Lmm6aaGEuaIkOS6uuaVmeiCsuWtpumZohLlpKfmsJTniannkIblrabpmaIM5ruo5rGf5a2m6ZmiG+eJqeeQhuS4juWFieeUteW3peeoi+WtpumZohXlnLDnkIbkuI7pgaXmhJ/lrabpmaIb546v5aKD56eR5a2m5LiO5bel56iL5a2m6ZmiFeaVsOWtpuS4jue7n+iuoeWtpumZogblm6Llp5QP5a2m55Sf5bel5L2c5aSECeWuoeiuoeWkhBXmu6jmsZ/lrabpmaLnkIblrabns7sY5ruo5rGf5a2m6Zmi6K6h566X5py657O7Hua7qOaxn+WtpumZoue7j+a1juS4jui0uOaYk+ezuxXmu6jmsZ/lrabpmaLlpJbor63ns7sb5ruo5rGf5a2m6Zmi5YWs5YWx566h55CG57O7Fea7qOaxn+WtpumZouS8muiuoeezuxvmu6jmsZ/lrabpmaLnlLXlrZDlt6XnqIvns7se5ruo5rGf5a2m6Zmi5aSn5rCU5LiO6YGl5oSf57O7G+a7qOaxn+WtpumZouiHquWKqOaOp+WItuezuwnkurrmrabpg6gP5aSn5a2m6Iux6K+t6YOoIeaAneaDs+aUv+ayu+eQhuiuuuivvuaVmeiCsuS4reW/gxvmu6jmsZ/lrabpmaLoirHml5fokKXmoKHljLoBIBUnATACMDECMDICMDMCMDQCMDUCMDYCMDcCMDgCMDkCMTACMTECMTMCMTQCMTUCMTcCMTgCMTkCMjACMjECMjICMjMCMjUCMjYCMjcCNTECNTICNTMCNTQCNTUCNTYCNTcCNTgCNTkCODACODECODICOTkBIBQrAydnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2cWAQImZAIDDxAPFgIfAGRkEBUBASAVAQEgFCsDAWcWAWZkAgUPEA8WAh8AZGQQFQ8EMjAwNQQyMDA0BDIwMDMEMjAwMgQyMDA2BDIwMDcEMjAwOAQyMDA5BDIwMTAEMjAxMQQyMDEyBDIwMTMEMjAxNAQyMDE1ASAVDwQyMDA1BDIwMDQEMjAwMwQyMDAyBDIwMDYEMjAwNwQyMDA4BDIwMDkEMjAxMAQyMDExBDIwMTIEMjAxMwQyMDE0BDIwMTUBIBQrAw9nZ2dnZ2dnZ2dnZ2dnZ2cWAQIOZAIHDxAPFgIfAGRkEBWFCAkxMOWKqOa8qzEJMTDliqjmvKsyCTEw5rOV5a2mMQkxMOmYsumbtzEJMTDlm73otLgxCTEw5Zu96LS4MgkxMOWMluWtpjEJMTDkvJrorqExCTEw5Lya6K6hMgkxMOS8muiuoTMJMTDkvJrorqE0CTEw5Lya6K6hNQkxMOiuoeenkTEPMTDkurrotYTlhazlhbExDzEw5Lq66LWE5YWs5YWxMg8xMOS6uui1hOS8geS4mjEPMTDkurrotYTkvIHkuJoyCTEw5pel6K+tMQkxMOaXpeivrTIJMTDova/ku7YxCTEw6L2v5Lu2Mg8xMOWVhuWKoeaXpeivrTEPMTDllYbliqHml6Xor60yDzEw5ZWG5Yqh6Iux6K+tMQ8xMOWVhuWKoeiLseivrTIJMTDlrp7pqowxCTEw5a6e6aqMMgkxMOWunumqjDMJMTDlrp7pqow0CTEw5a6e6aqMNQkxMOWunumqjDYJMTDpgJrkv6ExCTEw572R57ucMQkxMOe9kee7nDIJMTDniannkIYxCTEw54mp5rWBMQkxMOeJqea1gTIJMTDns7vnu58xCTEw5L+h5belMQkxMOS/oeW3pTIJMTDkv6HnrqExCTEw5L+h6K6hMQkxMOmBpeaEnzEJMTDoi7Hor60xCTEw6Iux6K+tMg8xMOiLseivree/u+ivkTEJMTDokKXplIAxCTEw6JCl6ZSAMgwxMOiHquWKqOWMljEf5rWL5o6n5oqA5pyv5LiO5Luq5ZmoMjAwOCgyKeePrSLnlLXmsJTlt6XnqIvkuI7oh6rliqjljJYyMDA4KDQp54+tH+eUteWtkOenkeWtpuS4juaKgOacrzIwMDgoMynnj60c55S15a2Q5L+h5oGv5bel56iLMjAwOCgzKeePrRznlLXlrZDkv6Hmga/lt6XnqIsyMDA4KDQp54+tH+WbvemZhee7j+a1juS4jui0uOaYkzIwMDgoMynnj60T5Lya6K6h5a2mMjAwOCg1KeePrR/ms5XlraYwOSgxKeePrSjoirHml5fokKXmoKHljLopFOa1i+e7mOW3peeoizA1KDEp54+tHea1i+aOp+aKgOacr+S4juS7quWZqDA1KDIp54+tHea1i+aOp+aKgOacr+S4juS7quWZqDA1KDEp54+tGuWcsOeQhuS/oeaBr+ezu+e7nzA1KDEp54+tIOeUteawlOW3peeoi+S4juiHquWKqOWMljA1KDIp54+tIOeUteawlOW3peeoi+S4juiHquWKqOWMljA1KDEp54+tHeeUteWtkOenkeWtpuS4juaKgOacrzA1KDIp54+tHeeUteWtkOenkeWtpuS4juaKgOacrzA1KDEp54+tGueUteWtkOS/oeaBr+W3peeoizA1KDIp54+tGueUteWtkOS/oeaBr+W3peeoizA1KDEp54+tDuazleWtpjA1KDIp54+tDuazleWtpjA1KDEp54+tHeWbvemZhee7j+a1juS4jui0uOaYkzA1KDMp54+tHeWbvemZhee7j+a1juS4jui0uOaYkzA1KDIp54+tHeWbvemZhee7j+a1juS4jui0uOaYkzA1KDEp54+tFOeOr+Wig+W3peeoizA1KDEp54+tEeS8muiuoeWtpjA1KDIp54+tEeS8muiuoeWtpjA1KDEp54+tIOiuoeeul+acuuenkeWtpuS4juaKgOacrzA1KDIp54+tIOiuoeeul+acuuenkeWtpuS4juaKgOacrzA1KDEp54+tI+mbt+eUtemYsuaKpOenkeWtpuS4juaKgOacrzA1KDIp54+tI+mbt+eUtemYsuaKpOenkeWtpuS4juaKgOacrzA1KDEp54+tQOS6uuWKm+i1hOa6kOeuoeeQhijlhazlhbHpg6jpl6jkurrlipvotYTmupDnrqHnkIbmlrnlkJEpMDUoMSnnj6065Lq65Yqb6LWE5rqQ566h55CGKOS8geS4muS6uuWKm+i1hOa6kOeuoeeQhuaWueWQkSkwNSgxKeePrQ7ml6Xor60wNSgyKeePrQ7ml6Xor60wNSgxKeePrSLml6Xor60o5Zu96ZmF5ZWG5Yqh5pa55ZCRKTA1KDIp54+tIuaXpeivrSjlm73pmYXllYbliqHmlrnlkJEpMDUoMSnnj60U6L2v5Lu25bel56iLMDUoMinnj60U6L2v5Lu25bel56iLMDUoMSnnj60U5biC5Zy66JCl6ZSAMDUoMSnnj60U6YCa5L+h5bel56iLMDUoMinnj60U6YCa5L+h5bel56iLMDUoMSnnj60U572R57uc5bel56iLMDUoMinnj60U572R57uc5bel56iLMDUoMSnnj60U54mp5rWB566h55CGMDUoMinnj60U54mp5rWB566h55CGMDUoMSnnj60U5L+h5oGv5bel56iLMDUoMSnnj60o5L+h5oGv5bel56iLKOezu+e7n+W3peeoi+aWueWQkSkwNSgyKeePrSjkv6Hmga/lt6XnqIso57O757uf5bel56iL5pa55ZCRKTA1KDEp54+tI+S/oeaBr+euoeeQhuS4juS/oeaBr+ezu+e7nzA1KDIp54+tHeS/oeaBr+S4juiuoeeul+enkeWtpjA1KDEp54+tHemBpeaEn+enkeWtpuS4juaKgOacrzA1KDEp54+tF+W6lOeUqOeJqeeQhuWtpjA1KDEp54+tDuiLseivrTA1KDEp54+tEeiHquWKqOWMljA1KDEp54+tFOS/oeaBr+W3peeoizA3KDIp54+tKOS/oeaBr+W3peeoiyjns7vnu5/lt6XnqIvmlrnlkJEpMDcoMSnnj60o5L+h5oGv5bel56iLKOezu+e7n+W3peeoi+aWueWQkSkwNygyKeePrSPkv6Hmga/nrqHnkIbkuI7kv6Hmga/ns7vnu58wNygxKeePrSPkv6Hmga/nrqHnkIbkuI7kv6Hmga/ns7vnu58wNygyKeePrR3kv6Hmga/kuI7orqHnrpfnp5HlraYwNygxKeePrR3pgaXmhJ/np5HlrabkuI7mioDmnK8wNygxKeePrR3pgaXmhJ/np5HlrabkuI7mioDmnK8wNygyKeePrRflupTnlKjniannkIblraYwNygxKeePrQ7oi7Hor60wNygxKeePrQ7oi7Hor60wNygyKeePrSLoi7Hor60o5Zu96ZmF5ZWG5Yqh5pa55ZCRKTA3KDEp54+tIuiLseivrSjlm73pmYXllYbliqHmlrnlkJEpMDcoMinnj60R6Ieq5Yqo5YyWMDcoMSnnj60R6Ieq5Yqo5YyWMDcoMinnj60a55S15a2Q5L+h5oGv5bel56iLMDUoMynnj60a55S15a2Q5L+h5oGv5bel56iLMDUoNCnnj60R5Lya6K6h5a2mMDUoMynnj60g6K6h566X5py656eR5a2m5LiO5oqA5pyvMDUoMynnj60g6K6h566X5py656eR5a2m5LiO5oqA5pyvMDUoNCnnj60U6YCa5L+h5bel56iLMDUoMynnj60O6Iux6K+tMDUoMynnj60O6Iux6K+tMDUoNCnnj60d55S15a2Q56eR5a2m5LiO5oqA5pyvMDYoMSnnj60l5Lya6K6h5a2mKOi0ouWKoeeuoeeQhuaWueWQkSkwNigxKeePrQ7oi7Hor60wNSgyKeePrS7oh6rliqjljJYo5rWL5o6n5oqA5pyv5LiO5Luq5Zmo5pa55ZCRKTA2KDEp54+tLuiHquWKqOWMlijmtYvmjqfmioDmnK/kuI7ku6rlmajmlrnlkJEpMDYoMinnj60a5Zyw55CG5L+h5oGv57O757ufMDYoMSnnj60g55S15rCU5bel56iL5LiO6Ieq5Yqo5YyWMDYoMSnnj60g55S15rCU5bel56iL5LiO6Ieq5Yqo5YyWMDYoMinnj60U5rWL57uY5bel56iLMDYoMSnnj60a55S15a2Q5L+h5oGv5bel56iLMDYoMinnj60955S15a2Q5L+h5oGv5bel56iLKOmbt+eUtemYsuaKpOenkeWtpuS4juaKgOacr+aWueWQkSkwNigxKeePrT3nlLXlrZDkv6Hmga/lt6XnqIso6Zu355S16Ziy5oqk56eR5a2m5LiO5oqA5pyv5pa55ZCRKTA2KDIp54+tDuazleWtpjA2KDEp54+tHeWbvemZhee7j+a1juS4jui0uOaYkzA2KDEp54+tHeWbvemZhee7j+a1juS4jui0uOaYkzA2KDIp54+tHeWbvemZhee7j+a1juS4jui0uOaYkzA2KDMp54+tEeS8muiuoeWtpjA2KDEp54+tEeS8muiuoeWtpjA2KDIp54+tIOiuoeeul+acuuenkeWtpuS4juaKgOacrzA2KDEp54+tIOiuoeeul+acuuenkeWtpuS4juaKgOacrzA2KDIp54+tNOiuoeeul+acuuenkeWtpuS4juaKgOacryjnvZHnu5zlt6XnqIvmlrnlkJEpMDYoMSnnj6006K6h566X5py656eR5a2m5LiO5oqA5pyvKOe9kee7nOW3peeoi+aWueWQkSkwNigyKeePrUDkurrlipvotYTmupDnrqHnkIYo5YWs5YWx6YOo6Zeo5Lq65Yqb6LWE5rqQ566h55CG5pa55ZCRKTA2KDEp54+tOuS6uuWKm+i1hOa6kOeuoeeQhijkvIHkuJrkurrlipvotYTmupDnrqHnkIbmlrnlkJEpMDYoMSnnj60O5pel6K+tMDYoMSnnj60O5pel6K+tMDYoMinnj60U6L2v5Lu25bel56iLMDYoMSnnj60U6L2v5Lu25bel56iLMDYoMinnj60i5pel6K+tKOWbvemZheWVhuWKoeaWueWQkSkwNigxKeePrRHoh6rliqjljJYwNigyKeePrSPkv6Hmga/nrqHnkIbkuI7kv6Hmga/ns7vnu58wNigyKeePrRrnlLXlrZDkv6Hmga/lt6XnqIswNigxKeePrSjkv6Hmga/lt6XnqIso57O757uf5bel56iL5pa55ZCRKTA2KDIp54+tI+S/oeaBr+euoeeQhuS4juS/oeaBr+ezu+e7nzA2KDEp54+tHea1i+aOp+aKgOacr+S4juS7quWZqDA3KDEp54+tHea1i+aOp+aKgOacr+S4juS7quWZqDA3KDIp54+tGuWcsOeQhuS/oeaBr+ezu+e7nzA3KDEp54+tGuWcsOeQhuS/oeaBr+ezu+e7nzA3KDIp54+tIOeUteawlOW3peeoi+S4juiHquWKqOWMljA3KDEp54+tIOeUteawlOW3peeoi+S4juiHquWKqOWMljA3KDIp54+tHeWbvemZhee7j+a1juS4jui0uOaYkzA1KDQp54+tHeWbvemZhee7j+a1juS4jui0uOaYkzA1KDUp54+tFOa1i+e7mOW3peeoizA3KDEp54+tFOa1i+e7mOW3peeoizA3KDIp54+tHeeUteWtkOenkeWtpuS4juaKgOacrzA3KDEp54+tHeeUteWtkOenkeWtpuS4juaKgOacrzA3KDIp54+tGueUteWtkOS/oeaBr+W3peeoizA3KDEp54+tGueUteWtkOS/oeaBr+W3peeoizA3KDIp54+tPeeUteWtkOS/oeaBr+W3peeoiyjpm7fnlLXpmLLmiqTnp5HlrabkuI7mioDmnK/mlrnlkJEpMDcoMSnnj60955S15a2Q5L+h5oGv5bel56iLKOmbt+eUtemYsuaKpOenkeWtpuS4juaKgOacr+aWueWQkSkwNygyKeePrT3nlLXlrZDkv6Hmga/lt6XnqIso6Zu355S16Ziy5oqk56eR5a2m5LiO5oqA5pyv5pa55ZCRKTA3KDMp54+tDuazleWtpjA3KDEp54+tDuazleWtpjA3KDIp54+tHeWbvemZhee7j+a1juS4jui0uOaYkzA3KDEp54+tHeWbvemZhee7j+a1juS4jui0uOaYkzA3KDIp54+tHeWbvemZhee7j+a1juS4jui0uOaYkzA3KDMp54+tEeS8muiuoeWtpjA3KDEp54+tEeS8muiuoeWtpjA3KDIp54+tEeS8muiuoeWtpjA3KDMp54+tEeS8muiuoeWtpjA3KDQp54+tJeS8muiuoeWtpijotKLliqHnrqHnkIbmlrnlkJEpMDcoMSnnj60l5Lya6K6h5a2mKOi0ouWKoeeuoeeQhuaWueWQkSkwNygyKeePrSDorqHnrpfmnLrnp5HlrabkuI7mioDmnK8wNygxKeePrSDorqHnrpfmnLrnp5HlrabkuI7mioDmnK8wNygyKeePrUDkurrlipvotYTmupDnrqHnkIYo5YWs5YWx6YOo6Zeo5Lq65Yqb6LWE5rqQ566h55CG5pa55ZCRKTA3KDIp54+tOuS6uuWKm+i1hOa6kOeuoeeQhijkvIHkuJrkurrlipvotYTmupDnrqHnkIbmlrnlkJEpMDcoMSnnj60O5pel6K+tMDcoMSnnj60O5pel6K+tMDcoMinnj60i5pel6K+tKOWbvemZheWVhuWKoeaWueWQkSkwNygxKeePrSLml6Xor60o5Zu96ZmF5ZWG5Yqh5pa55ZCRKTA3KDIp54+tFOi9r+S7tuW3peeoizA3KDEp54+tFOi9r+S7tuW3peeoizA3KDIp54+tEeWunumqjOePrTA3KDIp54+tEeWunumqjOePrTA3KDMp54+tFOW4guWcuuiQpemUgDA3KDIp54+tFOmAmuS/oeW3peeoizA3KDIp54+tFOe9kee7nOW3peeoizA3KDEp54+tFOeJqea1geeuoeeQhjA3KDEp54+tFOeJqea1geeuoeeQhjA3KDIp54+tFOS/oeaBr+W3peeoizA1KDIp54+tI+S/oeaBr+euoeeQhuS4juS/oeaBr+ezu+e7nzA1KDEp54+tIuiLseivrSjlm73pmYXllYbliqHmlrnlkJEpMDcoMynnj60R6Ieq5Yqo5YyWMDYoMynnj60R6Ieq5Yqo5YyWMDYoNCnnj60a55S15a2Q5L+h5oGv5bel56iLMDYoNCnnj60a55S15a2Q5L+h5oGv5bel56iLMDYoMynnj60d5Zu96ZmF57uP5rWO5LiO6LS45piTMDYoNCnnj60U5L+h5oGv5bel56iLMDYoMynnj60U5biC5Zy66JCl6ZSAMDYoMynnj60O5pel6K+tMDYoMynnj60g6K6h566X5py656eR5a2m5LiO5oqA5pyvMDYoMynnj60g6K6h566X5py656eR5a2m5LiO5oqA5pyvMDYoNCnnj60O6Iux6K+tMDYoMynnj60O6Iux6K+tMDYoNCnnj60R5Lya6K6h5a2mMDYoMynnj60R5Lya6K6h5a2mMDYoNCnnj60T5a6e6aqM54+tMjAwOCgxKeePrRPlrp7pqoznj60yMDA4KDMp54+tE+WunumqjOePrTIwMDgoNCnnj60W5aSn5rCU56eR5a2mMjAwOCgyKeePrRblpKfmsJTnp5HlraYyMDA4KDQp54+tHOeUteWtkOS/oeaBr+W3peeoizIwMDgoMSnnj60l5L+h5oGv566h55CG5LiO5L+h5oGv57O757ufMjAwOCgxKeePrSLorqHnrpfmnLrnp5HlrabkuI7mioDmnK8yMDA4KDEp54+tIuiuoeeul+acuuenkeWtpuS4juaKgOacrzIwMDgoMinnj60Q6Iux6K+tMjAwOCgxKeePrSToi7Hor60o5Zu96ZmF5ZWG5Yqh5pa55ZCRKTIwMDgoMSnnj60k6Iux6K+tKOWbvemZheWVhuWKoeaWueWQkSkyMDA4KDIp54+tE+S8muiuoeWtpjIwMDgoMinnj60T5Lya6K6h5a2mMjAwOCg0KeePrR/kv6Hmga/kuI7orqHnrpfnp5HlraYyMDA4KDEp54+tH+eUteWtkOenkeWtpuS4juaKgOacrzIwMDgoMSnnj60Q5pel6K+tMjAwOCgxKeePrRDml6Xor60yMDA4KDIp54+tJOaXpeivrSjlm73pmYXllYbliqHmlrnlkJEpMjAwOCgyKeePrRTluILlnLrokKXplIAwOSgyKeePrRTpgJrkv6Hlt6XnqIswOSgxKeePrRTpgJrkv6Hlt6XnqIswOSgyKeePrRTnvZHnu5zlt6XnqIswOSgxKeePrRTnvZHnu5zlt6XnqIswOSgyKeePrRTnianmtYHnrqHnkIYwOSgxKeePrRTnianmtYHnrqHnkIYwOSgyKeePrSjkv6Hmga/lt6XnqIso57O757uf5bel56iL5pa55ZCRKTA5KDEp54+tFOS/oeaBr+W3peeoizA5KDEp54+tI+S/oeaBr+euoeeQhuS4juS/oeaBr+ezu+e7nzA5KDEp54+tHeS/oeaBr+S4juiuoeeul+enkeWtpjA5KDEp54+tHemBpeaEn+enkeWtpuS4juaKgOacrzA5KDEp54+tFOW6lOeUqOWMluWtpjA5KDEp54+tF+W6lOeUqOeJqeeQhuWtpjA5KDEp54+tIuiLseivrSjlm73pmYXllYbliqHmlrnlkJEpMDkoMSnnj60i6Iux6K+tKOWbvemZheWVhuWKoeaWueWQkSkwOSgyKeePrQ7oi7Hor60wOSgxKeePrQ7oi7Hor60wOSgyKeePrRHoh6rliqjljJYwOSgxKeePrRHoh6rliqjljJYwOSgyKeePrR3mtYvmjqfmioDmnK/kuI7ku6rlmagwNygzKeePrSDnlLXmsJTlt6XnqIvkuI7oh6rliqjljJYwNyg0KeePrR3nlLXlrZDnp5HlrabkuI7mioDmnK8wNygzKeePrRrnlLXlrZDkv6Hmga/lt6XnqIswNygzKeePrRHkvJrorqHlraYwNyg1KeePrSDorqHnrpfmnLrnp5HlrabkuI7mioDmnK8wNygzKeePrQ7ml6Xor60wNygzKeePrRTova/ku7blt6XnqIswNygzKeePrRTpgJrkv6Hlt6XnqIswNygzKeePrRTnvZHnu5zlt6XnqIswNygzKeePrRTnianmtYHnrqHnkIYwNygzKeePrQ7oi7Hor60wNygzKeePrRHoh6rliqjljJYwNygzKeePrSXova/ku7blt6XnqIswOSgxKeePrSjoirHml5fokKXmoKHljLopHeWbvemZhee7j+a1juS4jui0uOaYkzA3KDQp54+tIuiLseivrSjlm73pmYXllYbliqHmlrnlkJEpMDUoMSnnj60i6Iux6K+tKOWbvemZheWVhuWKoeaWueWQkSkwNSgyKeePrSXotKLliqHnrqHnkIYwOCgxKeePrSjoirHml5fokKXmoKHljLopLuWbvemZhee7j+a1juS4jui0uOaYkzA4KDEp54+tKOiKseaXl+iQpeagoeWMuikl6LSi5Yqh566h55CGMDgoMinnj60o6Iqx5peX6JCl5qCh5Yy6KS7lm73pmYXnu4/mtY7kuI7otLjmmJMwOCgyKeePrSjoirHml5fokKXmoKHljLopIuS8muiuoeWtpjA4KDEp54+tKOiKseaXl+iQpeagoeWMuiki5Lya6K6h5a2mMDgoMinnj60o6Iqx5peX6JCl5qCh5Yy6KTHorqHnrpfmnLrnp5HlrabkuI7mioDmnK8wOCgxKeePrSjoirHml5fokKXmoKHljLopMeiuoeeul+acuuenkeWtpuS4juaKgOacrzA4KDIp54+tKOiKseaXl+iQpeagoeWMuikl6L2v5Lu25bel56iLMDgoMSnnj60o6Iqx5peX6JCl5qCh5Yy6KSXova/ku7blt6XnqIswOCgyKeePrSjoirHml5fokKXmoKHljLopJei9r+S7tuW3peeoizA5KDIp54+tKOiKseaXl+iQpeagoeWMuikl54mp5rWB566h55CGMDgoMSnnj60o6Iqx5peX6JCl5qCh5Yy6KSXnianmtYHnrqHnkIYwOCgyKeePrSjoirHml5fokKXmoKHljLopH+iLseivrTA4KDEp54+tKOiKseaXl+iQpeagoeWMuikf6Iux6K+tMDgoMinnj60o6Iqx5peX6JCl5qCh5Yy6KTTkv6Hmga/nrqHnkIbkuI7kv6Hmga/ns7vnu58wOCgyKeePrSjoirHml5fokKXmoKHljLopH+azleWtpjA4KDIp54+tKOiKseaXl+iQpeagoeWMuilF5Lq65Yqb6LWE5rqQ566h55CGKOWFrOWFsemDqOmXqOS6uuWKm+i1hOa6kCkwOCgxKeePrSjoirHml5fokKXmoKHljLopReS6uuWKm+i1hOa6kOeuoeeQhijlhazlhbHpg6jpl6jkurrlipvotYTmupApMDgoMinnj60o6Iqx5peX6JCl5qCh5Yy6KR/ms5XlraYwOCgxKeePrSjoirHml5fokKXmoKHljLopJei0ouWKoeeuoeeQhjA5KDEp54+tKOiKseaXl+iQpeagoeWMuikl6LSi5Yqh566h55CGMDkoMinnj60o6Iqx5peX6JCl5qCh5Yy6KR/ms5XlraYwOSgxKeePrSjoirHml5fokKXmoKHljLopH+azleWtpjA5KDIp54+tKOiKseaXl+iQpeagoeWMuiku5Zu96ZmF57uP5rWO5LiO6LS45piTMDkoMSnnj60o6Iqx5peX6JCl5qCh5Yy6KS7lm73pmYXnu4/mtY7kuI7otLjmmJMwOSgyKeePrSjoirHml5fokKXmoKHljLopMeiuoeeul+acuuenkeWtpuS4juaKgOacrzA5KDEp54+tKOiKseaXl+iQpeagoeWMuiki5Lya6K6h5a2mMDkoMSnnj60o6Iqx5peX6JCl5qCh5Yy6KSLkvJrorqHlraYwOSgyKeePrSjoirHml5fokKXmoKHljLopMeiuoeeul+acuuenkeWtpuS4juaKgOacrzA5KDIp54+tKOiKseaXl+iQpeagoeWMuilF5Lq65Yqb6LWE5rqQ566h55CGKOWFrOWFsemDqOmXqOS6uuWKm+i1hOa6kCkwOSgxKeePrSjoirHml5fokKXmoKHljLopReS6uuWKm+i1hOa6kOeuoeeQhijlhazlhbHpg6jpl6jkurrlipvotYTmupApMDkoMinnj60o6Iqx5peX6JCl5qCh5Yy6KSXluILlnLrokKXplIAwOCgxKeePrSjoirHml5fokKXmoKHljLopJeW4guWcuuiQpemUgDA4KDIp54+tKOiKseaXl+iQpeagoeWMuikl5biC5Zy66JCl6ZSAMDkoMSnnj60o6Iqx5peX6JCl5qCh5Yy6KSXluILlnLrokKXplIAwOSgyKeePrSjoirHml5fokKXmoKHljLopJee9kee7nOW3peeoizA4KDEp54+tKOiKseaXl+iQpeagoeWMuik05L+h5oGv566h55CG5LiO5L+h5oGv57O757ufMDgoMSnnj60o6Iqx5peX6JCl5qCh5Yy6KSXnvZHnu5zlt6XnqIswOCgyKeePrSjoirHml5fokKXmoKHljLopNOS/oeaBr+euoeeQhuS4juS/oeaBr+ezu+e7nzA5KDEp54+tKOiKseaXl+iQpeagoeWMuik05L+h5oGv566h55CG5LiO5L+h5oGv57O757ufMDkoMinnj60o6Iqx5peX6JCl5qCh5Yy6KR/oi7Hor60wOSgxKeePrSjoirHml5fokKXmoKHljLopH+iLseivrTA5KDIp54+tKOiKseaXl+iQpeagoeWMuikl54mp5rWB566h55CGMDkoMSnnj60o6Iqx5peX6JCl5qCh5Yy6KSXnianmtYHnrqHnkIYwOSgyKeePrSjoirHml5fokKXmoKHljLopJee9kee7nOW3peeoizA5KDEp54+tKOiKseaXl+iQpeagoeWMuikl572R57uc5bel56iLMDkoMinnj60o6Iqx5peX6JCl5qCh5Yy6KTTkv6Hmga/nrqHnkIbkuI7kv6Hmga/ns7vnu58wNigxKeePrSjoirHml5fokKXmoKHljLopNOS/oeaBr+euoeeQhuS4juS/oeaBr+ezu+e7nzA2KDIp54+tKOiKseaXl+iQpeagoeWMuikf5rOV5a2mMDUoMSnnj60o6Iqx5peX6JCl5qCh5Yy6KR/ms5XlraYwNSgyKeePrSjoirHml5fokKXmoKHljLopH+azleWtpjA2KDEp54+tKOiKseaXl+iQpeagoeWMuikf5rOV5a2mMDYoMinnj60o6Iqx5peX6JCl5qCh5Yy6KR/ms5XlraYwNygxKeePrSjoirHml5fokKXmoKHljLopH+azleWtpjA3KDIp54+tKOiKseaXl+iQpeagoeWMuiku5Zu96ZmF57uP5rWO5LiO6LS45piTMDUoMSnnj60o6Iqx5peX6JCl5qCh5Yy6KS7lm73pmYXnu4/mtY7kuI7otLjmmJMwNSgyKeePrSjoirHml5fokKXmoKHljLopLuWbvemZhee7j+a1juS4jui0uOaYkzA2KDEp54+tKOiKseaXl+iQpeagoeWMuiku5Zu96ZmF57uP5rWO5LiO6LS45piTMDYoMinnj60o6Iqx5peX6JCl5qCh5Yy6KS7lm73pmYXnu4/mtY7kuI7otLjmmJMwNygxKeePrSjoirHml5fokKXmoKHljLopLuWbvemZhee7j+a1juS4jui0uOaYkzA3KDIp54+tKOiKseaXl+iQpeagoeWMuiki5Lya6K6h5a2mMDcoMSnnj60o6Iqx5peX6JCl5qCh5Yy6KSLkvJrorqHlraYwNygyKeePrSjoirHml5fokKXmoKHljLopMeiuoeeul+acuuenkeWtpuS4juaKgOacrzA1KDEp54+tKOiKseaXl+iQpeagoeWMuikx6K6h566X5py656eR5a2m5LiO5oqA5pyvMDUoMinnj60o6Iqx5peX6JCl5qCh5Yy6KTHorqHnrpfmnLrnp5HlrabkuI7mioDmnK8wNigxKeePrSjoirHml5fokKXmoKHljLopMeiuoeeul+acuuenkeWtpuS4juaKgOacrzA2KDIp54+tKOiKseaXl+iQpeagoeWMuikx6K6h566X5py656eR5a2m5LiO5oqA5pyvMDcoMSnnj60o6Iqx5peX6JCl5qCh5Yy6KTHorqHnrpfmnLrnp5HlrabkuI7mioDmnK8wNygyKeePrSjoirHml5fokKXmoKHljLopJei9r+S7tuW3peeoizA1KDEp54+tKOiKseaXl+iQpeagoeWMuikl6L2v5Lu25bel56iLMDUoMinnj60o6Iqx5peX6JCl5qCh5Yy6KSXova/ku7blt6XnqIswNigxKeePrSjoirHml5fokKXmoKHljLopJei9r+S7tuW3peeoizA2KDIp54+tKOiKseaXl+iQpeagoeWMuikl6L2v5Lu25bel56iLMDcoMSnnj60o6Iqx5peX6JCl5qCh5Yy6KSXova/ku7blt6XnqIswNygyKeePrSjoirHml5fokKXmoKHljLopJeW4guWcuuiQpemUgDA3KDEp54+tKOiKseaXl+iQpeagoeWMuikl5biC5Zy66JCl6ZSAMDcoMinnj60o6Iqx5peX6JCl5qCh5Yy6KSXnvZHnu5zlt6XnqIswNygxKeePrSjoirHml5fokKXmoKHljLopJee9kee7nOW3peeoizA3KDIp54+tKOiKseaXl+iQpeagoeWMuikl54mp5rWB566h55CGMDcoMSnnj60o6Iqx5peX6JCl5qCh5Yy6KSXnianmtYHnrqHnkIYwNygyKeePrSjoirHml5fokKXmoKHljLopNOS/oeaBr+euoeeQhuS4juS/oeaBr+ezu+e7nzA1KDEp54+tKOiKseaXl+iQpeagoeWMuik05L+h5oGv566h55CG5LiO5L+h5oGv57O757ufMDUoMinnj60o6Iqx5peX6JCl5qCh5Yy6KTTkv6Hmga/nrqHnkIbkuI7kv6Hmga/ns7vnu58wNygxKeePrSjoirHml5fokKXmoKHljLopNOS/oeaBr+euoeeQhuS4juS/oeaBr+ezu+e7nzA3KDIp54+tKOiKseaXl+iQpeagoeWMuikf6Iux6K+tMDUoMSnnj60o6Iqx5peX6JCl5qCh5Yy6KR/oi7Hor60wNSgyKeePrSjoirHml5fokKXmoKHljLopH+iLseivrTA2KDEp54+tKOiKseaXl+iQpeagoeWMuikf6Iux6K+tMDYoMinnj60o6Iqx5peX6JCl5qCh5Yy6KR/oi7Hor60wNygxKeePrSjoirHml5fokKXmoKHljLopH+iLseivrTA3KDIp54+tKOiKseaXl+iQpeagoeWMuikj6Zu355S16Ziy5oqk56eR5a2m5LiO5oqA5pyvMDkoMSnnj60j6Zu355S16Ziy5oqk56eR5a2m5LiO5oqA5pyvMDkoMinnj60i55S15rCU5bel56iL5LiO6Ieq5Yqo5YyWMjAwOCgzKeePrT/nlLXlrZDkv6Hmga/lt6XnqIso6Zu355S16Ziy5oqk56eR5a2m5LiO5oqA5pyv5pa55ZCRKTIwMDgoMSnnj60/55S15a2Q5L+h5oGv5bel56iLKOmbt+eUtemYsuaKpOenkeWtpuS4juaKgOacr+aWueWQkSkyMDA4KDIp54+tCTEw6LSi566hMQkxMOi0oueuoTIJMTDmtYvnu5gxCTEw5rWL5o6nMQkxMOWkp+awlDEJMTDlpKfmsJQyCTEw5aSn5rCUMwkxMOWcsOS/oTEJMTDnlLXnp5ExCTEw55S15rCUMQkxMOeUteS/oTEJMTDnlLXkv6EyCTEx55S156eRMgkxMeeJqea1gTEJMTHnianmtYEyCTEx57O757ufMQkxMeS/oeW3pTEJMTHkv6Hlt6UyCTEx5L+h566hMQkxMeS/oeiuoTEJMTHpgaXmhJ8xCTEx6Iux6K+tMQkxMeiLseivrTIPMTHoi7Hor63nv7vor5ExCTEx6JCl6ZSAMQkxMeiQpemUgDIMMTHoh6rliqjljJYxETEx6LSi566hMVvoirHml5ddETEx5rOV5a2mMVvoirHml5ddETEx5Zu96LS4MVvoirHml5ddETEx5Lya6K6hMVvoirHml5ddETEx6K6h56eRMVvoirHml5ddFzEx5Lq66LWE5YWs5YWxMVvoirHml5ddFzEx5Lq66LWE5LyB5LiaMVvoirHml5ddETEx5pel6K+tMVvoirHml5ddETEx6L2v5belMVvoirHml5ddETEx54mp5rWBMVvoirHml5ddETEx5L+h566hMVvoirHml5ddETEx6Iux6K+tMVvoirHml5ddETEx6JCl6ZSAMVvoirHml5ddCTEx6YGl5oSfMgkxMemAmuS/oTIMMTHoh6rliqjljJYyCTEx5rOV5a2mMgkxMeWcsOS/oTIJMTHpmLLpm7cyCTEx55S15rCUMgkxMeiuoeenkTIJMTHlrp7pqowxQOS6uuWKm+i1hOa6kOeuoeeQhijlhazlhbHpg6jpl6jkurrlipvotYTmupDnrqHnkIbmlrnlkJEpMDcoMSnnj6065Lq65Yqb6LWE5rqQ566h55CGKOS8geS4muS6uuWKm+i1hOa6kOeuoeeQhuaWueWQkSkwNygyKeePrRHlrp7pqoznj60wNygxKeePrRTluILlnLrokKXplIAwNygxKeePrRTpgJrkv6Hlt6XnqIswNygxKeePrRTnvZHnu5zlt6XnqIswNygyKeePrRTkv6Hmga/lt6XnqIswNygxKeePrR3lm73pmYXnu4/mtY7kuI7otLjmmJMwNig1KeePrRPlrp7pqoznj60yMDA4KDIp54+tFuWkp+awlOenkeWtpjIwMDgoMSnnj60W5aSn5rCU56eR5a2mMjAwOCgzKeePrRznlLXlrZDkv6Hmga/lt6XnqIsyMDA4KDIp54+tJeS/oeaBr+euoeeQhuS4juS/oeaBr+ezu+e7nzIwMDgoMinnj60W5L+h5oGv5bel56iLMjAwOCgxKeePrRDoi7Hor60yMDA4KDIp54+tE+S8muiuoeWtpjIwMDgoMSnnj60T5Lya6K6h5a2mMjAwOCgzKeePrRzlnLDnkIbkv6Hmga/ns7vnu58yMDA4KDEp54+tH+eUteWtkOenkeWtpuS4juaKgOacrzIwMDgoMinnj60k5pel6K+tKOWbvemZheWVhuWKoeaWueWQkSkyMDA4KDEp54+tFOWkp+awlOenkeWtpjA5KDMp54+tIOiuoeeul+acuuenkeWtpuS4juaKgOacrzA5KDIp54+tGueUteWtkOS/oeaBr+W3peeoizA5KDMp54+tFOi0ouWKoeeuoeeQhjA5KDQp54+tHea1i+aOp+aKgOacr+S4juS7quWZqDA5KDIp54+tIOeUteawlOW3peeoi+S4juiHquWKqOWMljA5KDQp54+tHeeUteWtkOenkeWtpuS4juaKgOacrzA5KDMp54+tIOiuoeeul+acuuenkeWtpuS4juaKgOacrzA5KDMp54+tOuS6uuWKm+i1hOa6kOeuoeeQhijkvIHkuJrkurrlipvotYTmupDnrqHnkIbmlrnlkJEpMDkoMinnj60O5pel6K+tMDkoMynnj60U6L2v5Lu25bel56iLMDkoMynnj60U5biC5Zy66JCl6ZSAMDkoMynnj60U6YCa5L+h5bel56iLMDkoMynnj60U572R57uc5bel56iLMDkoMynnj60U54mp5rWB566h55CGMDkoMynnj60O6Iux6K+tMDkoMynnj60R6Ieq5Yqo5YyWMDkoMynnj60Q6YeN5paw5a2m5Lmg54+tMRDph43mlrDlrabkuaDnj60yETEx5Zyw5L+hMVvoirHml5ddETEx5pel5ZWGMVvoirHml5ddCTEy55S15rCUMgkxMueUteenkTEJMTLnlLXnp5EyCTEy55S15L+hMgkxMueUteS/oTEJMTLms5XlraYxDDEy54mp6IGU572RMgkxMueJqea1gTIJMTLnianmtYExCTEy5L+h5belMgkxMuS/oeW3pTEJMTLns7vnu58xETEx572R5belMVvoirHml5ddCTEy5L+h6K6hMRExMui0oueuoTFb6Iqx5peXXQkxMumBpeaEnzEJMTLljJblraYxCTEy6Iux6K+tMgkxMuiLseivrTEPMTLllYbliqHoi7Hor60yDzEy5ZWG5Yqh6Iux6K+tMQ8xMuiLseivree/u+ivkTERMTLlnLDkv6ExW+iKseaXl10RMTLms5XlraYxW+iKseaXl10MMTLoh6rliqjljJYxETEy5Zu96LS4MVvoirHml5ddCTEy6LSi566hMgkxMui0oueuoTEJMTLmtYvnu5gxCTEy5rWL5o6nMRExMuS8muiuoTFb6Iqx5peXXQkxMuWkp+awlDIJMTLlpKfmsJQxCTEy5Zyw5L+hMQkxMuWcsOS/oTIJMTLnlLXmsJQxCTEy5L+h566hMQkxMuS/oeeuoTIJMTLms5XlraYyDzEy57uZ5rC05o6S5rC0MQwxMuWFieS/oeaBrzEJMTLpgJrkv6EyCTEy572R57ucMgkxMue9kee7nDEMMTLnianogZTnvZExETEy6K6h56eRMVvoirHml5ddFzEy5Lq66LWE5YWs5YWxMVvoirHml5ddFzEy5Lq66LWE5LyB5LiaMVvoirHml5ddETEy5ZWG5pelMVvoirHml5ddETEy5pel6K+tMVvoirHml5ddETEy6L2v5Lu2MVvoirHml5ddCTEw5rWL5o6nMgkxMOeUteawlDMMMTDoh6rliqjljJYyCTEw55S156eRMgkxMOeUteS/oTMJMTDpgJrkv6EzCTEw6K6h56eRMgkxMOi9r+S7tjMJMTDnvZHnu5wzCTEw6LSi566hMwkxMOS8muiuoTYJMTDkvJrorqE3CTEw5Zu96LS4MwkxMOeJqea1gTMJMTDokKXplIAzDzEw5Lq66LWE5LyB5LiaMwkxMOaXpeivrTMJMTDoi7Hor60zETEy5ZWG6IuxMVvoirHml5ddETEy572R57ucMVvoirHml5ddFDEy54mp6IGU572RMVvoirHml5ddETEy54mp5rWBMVvoirHml5ddETEy5L+h566hMVvoirHml5ddETEy6Iux6K+tMVvoirHml5ddETEy6JCl6ZSAMVvoirHml5ddEOmHjeaWsOWtpuS5oOePrTEQ6YeN5paw5a2m5Lmg54+tMgkxM+eUteS/oTIRMTHllYboi7ExW+iKseaXl10JMTLlm73otLgyCTEy5Zu96LS4MQkxMuS8muiuoTUJMTLkvJrorqE0CTEy5Lya6K6hMwkxM+azleWtpjEJMTLml6Xor60xCTEz5rOV5a2mMg8xMuWVhuWKoeaXpeivrTEJMTLova/ku7YyCTEy6L2v5Lu2MQkxM+iLseivrTIJMTLliqjmvKsxCTEy5a6e6aqMNAkxMuWunumqjDMJMTLlrp7pqowyCTEy5a6e6aqMMQkxMuiQpemUgDIJMTLokKXplIAxCTEy6YCa5L+hMQ8xM+WVhuWKoeiLseivrTEPMTPllYbliqHoi7Hor60yDzEz6Iux6K+t57+76K+RMQkxM+WMluWtpjEJMTLkvJrorqEyCTEy5Lya6K6hMQkxMuiuoeenkTEJMTLorqHnp5EyCTEy6Ziy6Zu3MQkxMumYsumbtzIPMTLkurrotYTlhazlhbEyDzEy5Lq66LWE5YWs5YWxMQ8xMuS6uui1hOS8geS4mjIPMTLkurrotYTkvIHkuJoxDDEz57uZ5o6S5rC0MQwxM+WFieS/oeaBrzEJMTPkurrotYQyEOmHjeaWsOWtpuS5oOePrTEJMTPlm73otLgxCTEz5Zu96LS4MgkxM+S8muiuoTIJMTPkvJrorqEzCTEy6LSi566hMxDph43mlrDlrabkuaDnj60yDDEz6Ieq5Yqo5YyWMQwxM+iHquWKqOWMljIJMTPmtYvnu5gyDzEz6Iux6K+t57+76K+RMgkxM+aXpeivrTIJMTLnlLXmsJQzCTEy55S156eRMwkxMueUteS/oTMJMTLlm73otLgzCTEy5Lya6K6hNwkxMuiuoeenkTMJMTPlm73otLgzCTEz5Lya6K6hMQ8xMuS6uui1hOS8geS4mjMJMTLova/ku7YzCTEy6JCl6ZSAMwkxMumAmuS/oTMJMTLnianmtYEzCTEx6LSi566hMwkxMea1i+aOpzIJMTHnlLXmsJQzCTEx55S156eRMwkxMeeUteS/oTMJMTHlm73otLgzDDEy6Ieq5Yqo5YyWMgkxM+iuoeenkTEJMTPorqHnp5EyCTEz6YeR6J6NMQkxM+mHkeiejTIJMTPph5Hono0zCTEx5Lya6K6hNgkxMeiuoeenkTMPMTHkurrotYTkvIHkuJozCTEz5Lq66LWEMQkxM+aXpeivrTEJMTPova/ku7YxCTEx5pel6K+tMwkxM+WKqOa8qzEJMTPlrp7pqowxCTEz5a6e6aqMMgkxM+WunumqjDMJMTPlrp7pqow0CTEz6JCl6ZSAMQkxNOWunumqjDIMMTPnianogZTnvZEyCTEz6YCa5L+hMgkxM+iQpemUgDIJMTPmlbDlqpIxCTEz6YCa5L+hMQkxM+e9kee7nDEJMTPnianmtYEyDDE054mp6IGU572RMgwxM+eJqeiBlOe9kTEJMTPnianmtYExCTEz5L+h5belMQkxM+ezu+e7nzEMMTTnianogZTnvZExCTEx6L2v5Lu2MwkxMeiQpemUgDMJMTHpgJrkv6EzCTEx572R57ucMwkxMeeJqea1gTMJMTHoi7Hor60zDDEx6Ieq5Yqo5YyWMwkxM+mYsumbtzIJMTPpmLLpm7cxCTEz6LSi566hMQkxM+i0oueuoTIJMTPotKLnrqEzCTEz5rWL57uYMQkxM+a1i+aOpzEJMTTnianmtYEyCTEz5aSn5rCUMQkxM+Wkp+awlDIJMTPlnLDkv6ExCTEz5Zyw5L+hMgkxM+eUteawlDEJMTPnlLXmsJQyCTEz55S156eRMQkxM+eUteenkTIJMTPnlLXkv6ExCTEz5L+h566hMQkxNOeJqea1gTEJMTPkv6HorqExCTEz6YGl5oSfMQkxNOS/oeW3pTEJMTPoi7Hor60xCTE05L+h566hMQkxNOS/oeiuoTEJMTTpgaXmhJ8xCTE06Iux6K+tMhDph43mlrDlrabkuaDnj60xEOmHjeaWsOWtpuS5oOePrTIRMTPotKLnrqExW+iKseaXl10RMTPlnLDkv6ExW+iKseaXl10RMTPms5XlraYxW+iKseaXl10RMTPlm73otLgxW+iKseaXl10RMTPkvJrorqExW+iKseaXl10RMTPorqHnp5ExW+iKseaXl10RMTPkurrotYQxW+iKseaXl10RMTPml6Xor60xW+iKseaXl10RMTPova/lt6UxW+iKseaXl10RMTPokKXplIAxW+iKseaXl10RMTPnvZHlt6UxW+iKseaXl10UMTPnianogZTnvZExW+iKseaXl10RMTPnianmtYExW+iKseaXl10RMTPkv6HnrqExW+iKseaXl10RMTPoi7Hor60xW+iKseaXl10RMTPoi7HllYYxW+iKseaXl10RMTPph5Hono0xW+iKseaXl10RMTTotKLnrqExW+iKseaXl10RMTTlnLDkv6ExW+iKseaXl10RMTTms5XlraYxW+iKseaXl10RMTTlm73otLgxW+iKseaXl10RMTTkvJrorqExW+iKseaXl10RMTTorqHnp5ExW+iKseaXl10RMTTkurrotYQxW+iKseaXl10RMTTml6Xor60xW+iKseaXl10RMTTova/ku7YxW+iKseaXl10MMTHlhYnkv6Hmga8xCTE06LSi566hMgwxMee7meaOkuawtDEJMTTotKLnrqEzCTE06LSi566hNAkxM+eUteS/oTMJMTTmtYvmjqcxCTE06Iux6K+tMQkxNOWMluWtpjEMMTToh6rliqjljJYxCTEz6YCa5L+hMxExNOiQpemUgDFb6Iqx5peXXRExNOe9kee7nDFb6Iqx5peXXRQxNOeJqeiBlOe9kTFb6Iqx5peXXRExNOeJqea1gTFb6Iqx5peXXRExNOS/oeeuoTFb6Iqx5peXXRExNOiLseivrTFb6Iqx5peXXQkxNOWuieWFqDIJMTTlronlhagxCTE06LSi566hMQkxNOa1i+e7mDEJMTPkurrotYQzCTE05aSn5rCUMQkxNOWkp+awlDIJMTTlnLDkv6ExCTEz6LSi566hNAkxNOeUteawlDEJMTTnlLXmsJQyCTEz5Lya6K6hNAkxNOeUteenkTEJMTPorqHnp5EzCTE055S15L+hMgkxNOeUteS/oTEJMTTms5XlraYxCTE05rOV5a2mMgwxNOWFieS/oeaBrzEJMTTlm73otLgxCTE05Zu96LS4MgkxM+i9r+S7tjIJMTTkvJrorqEyCTE05Lya6K6hMwkxNOS8muiuoTEJMTTkvJrorqE0CTE06K6h56eRMQkxNOiuoeenkTIJMTTph5Hono0xCTE06YeR6J6NMgkxNOmHkeiejTMJMTTkurrotYQyCTE05Lq66LWEMQkxM+Wbvei0uDQJMTTml6Xor60xCTE06L2v5Lu2MQkxNOi9r+S7tjIJMTTlrp7pqowxCTE05a6e6aqMMwkxNOWunumqjDQJMTTokKXplIAxCTE06JCl6ZSAMgkxNOaVsOWqkjEJMTTmlbDlqpIyCTE06YCa5L+hMgkxNOmAmuS/oTEJMTTnvZHnu5wxCTE0572R57ucMhExNOmHkeiejTFb6Iqx5peXXQkxM+mHkeiejTQJMTPokKXplIAzCTEz54mp5rWBMwkxM+eUteawlDMMMTPoh6rliqjljJYzCTE15a6J5YWoMQkxNeWuieWFqDIJMTXotKLnrqEyCTE16LSi566hMwkxNei0oueuoTEJMTXotKLnrqE0CTE15rWL57uYMQkxNea1i+aOpzEJMTXlpKfmsJQyCTE15aSn5rCUMQkxNeWcsOS/oTEJMTXnlLXmsJQxCTE155S15rCUMgkxNeeUteenkTEJMTDnlLXmsJQyCTEw6Ziy6Zu3MgkxMOmAmuS/oTIJMTLkvJrorqE2CTE155S15L+hMgkxNeeUteS/oTEJMTXms5XlraYyCTE15rOV5a2mMQwxNeWFieS/oeaBrzEJMTXlm73otLgxCTE15Zu96LS4MgkxNeS8muiuoTQJMTXkvJrorqEyCTE15Lya6K6hMwkxNeS8muiuoTEJMTXorqHnp5ExCTE16K6h56eRMgkxNemHkeiejTERMTXotKLnrqExW+iKseaXl10JMTXph5Hono0yCTE15Lq66LWEMgkxNeS6uui1hDEJMTXml6Xor60xCTE16L2v5Lu2MgkxNei9r+S7tjEJMTXlrp7pqowyCTE15a6e6aqMMQkxNeiQpemUgDEJMTXokKXplIAyCTE15pWw5aqSMQkxNeaVsOWqkjIJMTXpgJrkv6EyCTE16YCa5L+hMQkxNee9kee7nDIJMTXnvZHnu5wxDDE154mp6IGU572RMQkxNeeJqea1gTIJMTXnianmtYExCTE15L+h5belMQkxNeS/oeeuoTEJMTXkv6HorqExCTE16YGl5oSfMQkxNeiLseivrTEJMTXoi7Hor60yCTE15YyW5a2mMQwxNeiHquWKqOWMljEQ6YeN5paw5a2m5Lmg54+tMhDph43mlrDlrabkuaDnj60xDzE16K6h56eR5bWM5YWlMQ8xNei9r+S7tuW1jOWFpTEMMTXoh6rliqjljJYyETE16LSi566hMlvoirHml5ddETE15rOV5a2mMVvoirHml5ddETE15Zu96LS4MVvoirHml5ddETE15Lya6K6hMVvoirHml5ddETE15Lya6K6hMlvoirHml5ddETE16K6h56eRMVvoirHml5ddETE16YeR6J6NMVvoirHml5ddETE15Lq66LWEMVvoirHml5ddETE15pel6K+tMVvoirHml5ddETE15pel6K+tMlvoirHml5ddETE16L2v5belMVvoirHml5ddETE15biC6JClMVvoirHml5ddETE1572R5belMVvoirHml5ddETE154mp5belMVvoirHml5ddETE154mp5rWBMVvoirHml5ddETE15L+h566hMVvoirHml5ddETE16Iux6K+tMVvoirHml5ddETE16Iux6K+tMlvoirHml5ddETE06Iux6K+tMlvoirHml5ddETE06LSi566hMlvoirHml5ddETE05Lya6K6hMlvoirHml5ddIuaXpeivrSjlm73pmYXllYbliqHmlrnlkJEpMDYoMinnj60R5a6e6aqM54+tMDYoMSnnj60R5a6e6aqM54+tMDYoMinnj60R5a6e6aqM54+tMDYoMynnj60U5biC5Zy66JCl6ZSAMDYoMSnnj60U5biC5Zy66JCl6ZSAMDYoMinnj60o5L+h5oGv5bel56iLKOmAmuS/oeW3peeoi+aWueWQkSkwNigxKeePrSjkv6Hmga/lt6XnqIso6YCa5L+h5bel56iL5pa55ZCRKTA2KDIp54+tFOeJqea1geeuoeeQhjA2KDEp54+tFOeJqea1geeuoeeQhjA2KDIp54+tFOS/oeaBr+W3peeoizA2KDEp54+tFOS/oeaBr+W3peeoizA2KDIp54+tKOS/oeaBr+W3peeoiyjns7vnu5/lt6XnqIvmlrnlkJEpMDYoMSnnj60d6YGl5oSf56eR5a2m5LiO5oqA5pyvMDYoMSnnj60d6YGl5oSf56eR5a2m5LiO5oqA5pyvMDYoMinnj60O6Iux6K+tMDYoMSnnj60O6Iux6K+tMDYoMinnj60i6Iux6K+tKOWbvemZheWVhuWKoeaWueWQkSkwNigxKeePrSLoi7Hor60o5Zu96ZmF5ZWG5Yqh5pa55ZCRKTA2KDIp54+tIuiLseivrSjlm73pmYXllYbliqHmlrnlkJEpMDYoMynnj60R6Ieq5Yqo5YyWMDYoMSnnj60q5L+h5oGv5bel56iLKOezu+e7n+W3peeoi+aWueWQkSkyMDA4KDEp54+tHeWbvemZhee7j+a1juS4jui0uOaYkzA5KDQp54+tEeS8muiuoeWtpjA5KDYp54+tGeW6lOeUqOeJqeeQhuWtpjIwMDgoMSnnj60Q5rOV5a2mMjAwOCgxKeePrR/lm73pmYXnu4/mtY7kuI7otLjmmJMyMDA4KDEp54+tH+WbvemZhee7j+a1juS4jui0uOaYkzIwMDgoMinnj6085Lq65Yqb6LWE5rqQ566h55CGKOS8geS4muS6uuWKm+i1hOa6kOeuoeeQhuaWueWQkSkyMDA4KDEp54+tPOS6uuWKm+i1hOa6kOeuoeeQhijkvIHkuJrkurrlipvotYTmupDnrqHnkIbmlrnlkJEpMjAwOCgyKeePrULkurrlipvotYTmupDnrqHnkIYo5YWs5YWx6YOo6Zeo5Lq65Yqb6LWE5rqQ566h55CG5pa55ZCRKTIwMDgoMSnnj60W5biC5Zy66JCl6ZSAMjAwOCgxKeePrRbluILlnLrokKXplIAyMDA4KDIp54+tFumAmuS/oeW3peeoizIwMDgoMSnnj60W6YCa5L+h5bel56iLMjAwOCgyKeePrR/pgaXmhJ/np5HlrabkuI7mioDmnK8yMDA4KDEp54+tE+iHquWKqOWMljIwMDgoMSnnj60T6Ieq5Yqo5YyWMjAwOCgyKeePrRblupTnlKjljJblraYyMDA4KDEp54+tFui0ouWKoeeuoeeQhjIwMDgoMSnnj60W6LSi5Yqh566h55CGMjAwOCgyKeePrSLnlLXmsJTlt6XnqIvkuI7oh6rliqjljJYyMDA4KDEp54+tIueUteawlOW3peeoi+S4juiHquWKqOWMljIwMDgoMinnj60f5rWL5o6n5oqA5pyv5LiO5Luq5ZmoMjAwOCgxKeePrRbova/ku7blt6XnqIsyMDA4KDEp54+tFui9r+S7tuW3peeoizIwMDgoMinnj60W572R57uc5bel56iLMjAwOCgxKeePrRbnvZHnu5zlt6XnqIsyMDA4KDIp54+tFueJqea1geeuoeeQhjIwMDgoMSnnj60W54mp5rWB566h55CGMjAwOCgyKeePrRbmtYvnu5jlt6XnqIsyMDA4KDEp54+tJOi9r+S7tuW3peeoiyjliqjnlLvmlrnlkJEpMjAwOCgxKeePrSTova/ku7blt6XnqIso5Yqo55S75pa55ZCRKTIwMDgoMinnj60g55S15rCU5bel56iL5LiO6Ieq5Yqo5YyWMDcoMynnj60T5a6e6aqM54+tMjAwOCg1KeePrRTotKLliqHnrqHnkIYwOSgxKeePrRTotKLliqHnrqHnkIYwOSgyKeePrRTotKLliqHnrqHnkIYwOSgzKeePrRTmtYvnu5jlt6XnqIswOSgxKeePrR3mtYvmjqfmioDmnK/kuI7ku6rlmagwOSgxKeePrRTlpKfmsJTnp5HlraYwOSgxKeePrRTlpKfmsJTnp5HlraYwOSgyKeePrRTlpKfmsJTnp5HlraYwOSg0KeePrRrlnLDnkIbkv6Hmga/ns7vnu58wOSgxKeePrSDnlLXmsJTlt6XnqIvkuI7oh6rliqjljJYwOSgxKeePrSDnlLXmsJTlt6XnqIvkuI7oh6rliqjljJYwOSgyKeePrR3nlLXlrZDnp5HlrabkuI7mioDmnK8wOSgxKeePrR3nlLXlrZDnp5HlrabkuI7mioDmnK8wOSgyKeePrRrnlLXlrZDkv6Hmga/lt6XnqIswOSgxKeePrRrnlLXlrZDkv6Hmga/lt6XnqIswOSgyKeePrQ7ms5XlraYwOSgxKeePrQ7ms5XlraYwOSgyKeePrR3lm73pmYXnu4/mtY7kuI7otLjmmJMwOSgxKeePrR3lm73pmYXnu4/mtY7kuI7otLjmmJMwOSgyKeePrR3lm73pmYXnu4/mtY7kuI7otLjmmJMwOSgzKeePrRHkvJrorqHlraYwOSgxKeePrRHkvJrorqHlraYwOSgyKeePrRHkvJrorqHlraYwOSgzKeePrRHkvJrorqHlraYwOSg0KeePrRHkvJrorqHlraYwOSg1KeePrSDorqHnrpfmnLrnp5HlrabkuI7mioDmnK8wOSgxKeePrUDkurrlipvotYTmupDnrqHnkIYo5YWs5YWx6YOo6Zeo5Lq65Yqb6LWE5rqQ566h55CG5pa55ZCRKTA5KDEp54+tOuS6uuWKm+i1hOa6kOeuoeeQhijkvIHkuJrkurrlipvotYTmupDnrqHnkIbmlrnlkJEpMDkoMSnnj60i5pel6K+tKOWbvemZheWVhuWKoeaWueWQkSkwOSgxKeePrSLml6Xor60o5Zu96ZmF5ZWG5Yqh5pa55ZCRKTA5KDIp54+tDuaXpeivrTA5KDEp54+tDuaXpeivrTA5KDIp54+tIui9r+S7tuW3peeoiyjliqjnlLvmlrnlkJEpMDkoMSnnj60i6L2v5Lu25bel56iLKOWKqOeUu+aWueWQkSkwOSgyKeePrRTova/ku7blt6XnqIswOSgxKeePrRTova/ku7blt6XnqIswOSgyKeePrRHlrp7pqoznj60wOSgxKeePrRHlrp7pqoznj60wOSgyKeePrRHlrp7pqoznj60wOSgzKeePrRHlrp7pqoznj60wOSg0KeePrRHlrp7pqoznj60wOSg1KeePrRHlrp7pqoznj60wOSg2KeePrRTluILlnLrokKXplIAwOSgxKeePrSLorqHnrpfmnLrnp5HlrabkuI7mioDmnK8yMDA4KDMp54+tEOaXpeivrTIwMDgoMynnj60W6L2v5Lu25bel56iLMjAwOCgzKeePrRbluILlnLrokKXplIAyMDA4KDMp54+tFumAmuS/oeW3peeoizIwMDgoMynnj60W572R57uc5bel56iLMjAwOCgzKeePrRbnianmtYHnrqHnkIYyMDA4KDMp54+tEOiLseivrTIwMDgoMynnj60T6Ieq5Yqo5YyWMjAwOCgzKeePrRExMOi0oueuoTFb6Iqx5peXXRExMOazleWtpjFb6Iqx5peXXRExMOWbvei0uDFb6Iqx5peXXRExMOS8muiuoTFb6Iqx5peXXRExMOiuoeenkTFb6Iqx5peXXRcxMOS6uui1hOWFrOWFsTFb6Iqx5peXXRcxMOS6uui1hOS8geS4mjFb6Iqx5peXXRExMOaXpeivrTFb6Iqx5peXXRExMOi9r+S7tjFb6Iqx5peXXRExMOe9kee7nDFb6Iqx5peXXRExMOeJqea1gTFb6Iqx5peXXRExMOS/oeeuoTFb6Iqx5peXXRExMOiLseivrTFb6Iqx5peXXRExMOiQpemUgDFb6Iqx5peXXSDnlLXmsJTlt6XnqIvkuI7oh6rliqjljJYwOSgzKeePrQkxMei0oueuoTEJMTHotKLnrqEyCTEx5rWL57uYMQkxMea1i+aOpzEJMTHlpKfmsJQxCTEx5aSn5rCUMgkxMeWkp+awlDMJMTHlnLDkv6ExCTEx55S156eRMQkxMeeUteawlDEJMTHnlLXkv6ExCTEx55S15L+hMgkxMeWKqOa8qzEJMTHms5XlraYxCTEx6Ziy6Zu3MQkxMeWbvei0uDEJMTHlm73otLgyCTEx5YyW5a2mMQkxMeS8muiuoTEJMTHkvJrorqEyCTEx5Lya6K6hMwkxMeS8muiuoTQJMTHkvJrorqE1CTEx6K6h56eRMQ8xMeS6uui1hOWFrOWFsTEPMTHkurrotYTlhazlhbEyDzEx5Lq66LWE5LyB5LiaMQ8xMeS6uui1hOS8geS4mjIJMTHml6Xor60xCTEx5pel6K+tMgkxMei9r+S7tjEJMTHova/ku7YyDzEx5ZWG5Yqh5pel6K+tMQ8xMeWVhuWKoeaXpeivrTIPMTHllYbliqHoi7Hor60xDzEx5ZWG5Yqh6Iux6K+tMgkxMeWunumqjDIJMTHlrp7pqowzCTEx5a6e6aqMNAkxMemAmuS/oTEJMTHnvZHnu5wxCTEx572R57ucMgEgFYUICDIzNTkxMDAxCDIzNTkxMDAyCDIzMjgxMDAxCDIzNDgxMDAxCDIzMzAxMDAxCDIzMzAxMDAyCDIzMzcxMDAxCDIzMTIxMDAxCDIzMTIxMDAyCDIzMTIxMDAzCDIzMTIxMDA0CDIzMTIxMDA1CDIzMDgxMDAxCDIzMzIxMDAxCDIzMzIxMDAyCDIzMzExMDAxCDIzMzExMDAyCDIzMjIxMDAxCDIzMjIxMDAyCDIzNDQxMDAxCDIzNDQxMDAyCDIzMjMxMDAxCDIzMjMxMDAyCDIzMTExMDAxCDIzMTExMDAyCDIzMDAxMDAxCDIzMDAxMDAyCDIzMDAxMDAzCDIzMDAxMDA0CDIzMDAxMDA1CDIzMDAxMDA2CDIzMzQxMDAxCDIzNDYxMDAxCDIzNDYxMDAyCDIzMjYxMDAxCDIzNDcxMDAxCDIzNDcxMDAyCDIzMjUxMDAxCDIzMDkxMDAxCDIzMDkxMDAyCDIzMDcxMDAxCDIzMTQxMDAxCDIzMzUxMDAxCDIzMTAxMDAxCDIzMTAxMDAyCDIzNjAxMDAxCDIzMzMxMDAxCDIzMzMxMDAyCDIzMzYxMDAxCDIzNDEwODAyCDIzNDAwODA0CDIzMjEwODAzCDIzMDUwODAzCDIzMDUwODA0CDIzMzAwODAzCDIzMTIwODA1CDgzMzkwNTAxCDIzNTAwNTAxCDIzNDEwNTAyCDIzNDEwNTAxCDIzMTYwNTAxCDIzNDAwNTAyCDIzNDAwNTAxCDIzMjEwNTAyCDIzMjEwNTAxCDIzMDUwNTAyCDIzMDUwNTAxCDIzMjgwNTAyCDIzMjgwNTAxCDIzMzAwNTAzCDIzMzAwNTAyCDIzMzAwNTAxCDIzNDMwNTAxCDIzMTIwNTAyCDIzMTIwNTAxCDIzMDgwNTAyCDIzMDgwNTAxCDIzNDUwNTAyCDIzNDUwNTAxCDIzMzIwNTAxCDIzMzEwNTAxCDIzMjIwNTAyCDIzMjIwNTAxCDIzMjMwNTAyCDIzMjMwNTAxCDIzNDQwNTAyCDIzNDQwNTAxCDIzMzMwNTAxCDIzMzQwNTAyCDIzMzQwNTAxCDIzNDYwNTAyCDIzNDYwNTAxCDIzNDcwNTAyCDIzNDcwNTAxCDIzMDkwNTAxCDIzMjUwNTAyCDIzMjUwNTAxCDIzMDcwNTAyCDIzMTQwNTAxCDIzMzUwNTAxCDIzMjYwNTAxCDIzMTAwNTAxCDIzMzYwNTAxCDIzMDkwNzAyCDIzMjUwNzAxCDIzMjUwNzAyCDIzMDcwNzAxCDIzMDcwNzAyCDIzMTQwNzAxCDIzMzUwNzAxCDIzMzUwNzAyCDIzMjYwNzAxCDIzMTAwNzAxCDIzMTAwNzAyCDIzMTEwNzAxCDIzMTEwNzAyCDIzMzYwNzAxCDIzMzYwNzAyCDIzMDUwNTAzCDIzMDUwNTA0CDIzMTIwNTAzCDIzMDgwNTAzCDIzMDgwNTA0CDIzMzQwNTAzCDIzMTAwNTAzCDIzMTAwNTA0CDIzMjEwNjAxCDIzOTIwNjAxCDIzMTAwNTAyCDIzOTQwNjAxCDIzOTQwNjAyCDIzMTYwNjAxCDIzNDAwNjAxCDIzNDAwNjAyCDIzNTAwNjAxCDIzMDUwNjAyCDIzOTMwNjAxCDIzOTMwNjAyCDIzMjkwNjAxCDIzMzAwNjAxCDIzMzAwNjAyCDIzMzAwNjAzCDIzMTIwNjAxCDIzMTIwNjAyCDIzMDgwNjAxCDIzMDgwNjAyCDIzOTUwNjAxCDIzOTUwNjAyCDIzOTAwNjAxCDIzMzEwNjAxCDIzMjIwNjAxCDIzMjIwNjAyCDIzNDQwNjAxCDIzNDQwNjAyCDIzMjMwNjAxCDIzMzYwNjAyCDIzMDcwNjAyCDIzMDUwNjAxCDIzMjUwNjAyCDIzMDcwNjAxCDIzNDEwNzAxCDIzNDEwNzAyCDIzMTYwNzAxCDIzMTYwNzAyCDIzNDAwNzAxCDIzNDAwNzAyCDIzMzAwNTA0CDIzMzAwNTA1CDIzNTAwNzAxCDIzNTAwNzAyCDIzMjEwNzAxCDIzMjEwNzAyCDIzMDUwNzAxCDIzMDUwNzAyCDIzOTMwNzAxCDIzOTMwNzAyCDIzOTMwNzAzCDIzMjgwNzAxCDIzMjgwNzAyCDIzMzAwNzAxCDIzMzAwNzAyCDIzMzAwNzAzCDIzMTIwNzAxCDIzMTIwNzAyCDIzMTIwNzAzCDIzMTIwNzA0CDIzOTIwNzAxCDIzOTIwNzAyCDIzMDgwNzAxCDIzMDgwNzAyCDIzMzIwNzAyCDIzMzEwNzAxCDIzMjIwNzAxCDIzMjIwNzAyCDIzMjMwNzAxCDIzMjMwNzAyCDIzNDQwNzAxCDIzNDQwNzAyCDIzMDAwNzAyCDIzMDAwNzAzCDIzMzMwNzAyCDIzMzQwNzAyCDIzNDYwNzAxCDIzNDcwNzAxCDIzNDcwNzAyCDIzMDkwNTAyCDIzMDcwNTAxCDIzMTEwNzAzCDIzMzYwNjAzCDIzMzYwNjA0CDIzMDUwNjA0CDIzMDUwNjAzCDIzMzAwNjA0CDIzMDkwNjAzCDIzMzMwNjAzCDIzMjIwNjAzCDIzMDgwNjAzCDIzMDgwNjA0CDIzMTAwNjAzCDIzMTAwNjA0CDIzMTIwNjAzCDIzMTIwNjA0CDIzMDAwODAxCDIzMDAwODAzCDIzMDAwODA0CDIzMDEwODAyCDIzMDEwODA0CDIzMDUwODAxCDIzMDcwODAxCDIzMDgwODAxCDIzMDgwODAyCDIzMTAwODAxCDIzMTEwODAxCDIzMTEwODAyCDIzMTIwODAyCDIzMTIwODA0CDIzMTQwODAxCDIzMjEwODAxCDIzMjIwODAxCDIzMjIwODAyCDIzMjMwODAyCDIzMzMwOTAyCDIzMzQwOTAxCDIzMzQwOTAyCDIzNDYwOTAxCDIzNDYwOTAyCDIzNDcwOTAxCDIzNDcwOTAyCDIzMjUwOTAxCDIzMDkwOTAxCDIzMDcwOTAxCDIzMTQwOTAxCDIzMzUwOTAxCDIzMzcwOTAxCDIzMjYwOTAxCDIzMTEwOTAxCDIzMTEwOTAyCDIzMTAwOTAxCDIzMTAwOTAyCDIzMzYwOTAxCDIzMzYwOTAyCDIzNDEwNzAzCDIzNDAwNzA0CDIzMjEwNzAzCDIzMDUwNzAzCDIzMTIwNzA1CDIzMDgwNzAzCDIzMjIwNzAzCDIzNDQwNzAzCDIzMzQwNzAzCDIzNDYwNzAzCDIzNDcwNzAzCDIzMTAwNzAzCDIzMzYwNzAzCDgzNDQwOTAxCDIzMzAwNzA0CDIzMTEwNTAxCDIzMTEwNTAyCDgzMzkwODAxCDgzMzAwODAxCDgzMzkwODAyCDgzMzAwODAyCDgzMTIwODAxCDgzMTIwODAyCDgzMDgwODAxCDgzMDgwODAyCDgzNDQwODAxCDgzNDQwODAyCDgzNDQwOTAyCDgzNDcwODAxCDgzNDcwODAyCDgzMTAwODAxCDgzMTAwODAyCDgzMDcwODAyCDgzMjgwODAyCDgzMzIwODAxCDgzMzIwODAyCDgzMjgwODAxCDgzMzkwOTAxCDgzMzkwOTAyCDgzMjgwOTAxCDgzMjgwOTAyCDgzMzAwOTAxCDgzMzAwOTAyCDgzMDgwOTAxCDgzMTIwOTAxCDgzMTIwOTAyCDgzMDgwOTAyCDgzMzIwOTAxCDgzMzIwOTAyCDgzMzMwODAxCDgzMzMwODAyCDgzMzMwOTAxCDgzMzMwOTAyCDgzNDYwODAxCDgzMDcwODAxCDgzNDYwODAyCDgzMDcwOTAxCDgzMDcwOTAyCDgzMTAwOTAxCDgzMTAwOTAyCDgzNDcwOTAxCDgzNDcwOTAyCDgzNDYwOTAxCDgzNDYwOTAyCDgzMDcwNjAxCDgzMDcwNjAyCDgzMjgwNTAxCDgzMjgwNTAyCDgzMjgwNjAxCDgzMjgwNjAyCDgzMjgwNzAxCDgzMjgwNzAyCDgzMzAwNTAxCDgzMzAwNTAyCDgzMzAwNjAxCDgzMzAwNjAyCDgzMzAwNzAxCDgzMzAwNzAyCDgzMTIwNzAxCDgzMTIwNzAyCDgzMDgwNTAxCDgzMDgwNTAyCDgzMDgwNjAxCDgzMDgwNjAyCDgzMDgwNzAxCDgzMDgwNzAyCDgzNDQwNTAxCDgzNDQwNTAyCDgzNDQwNjAxCDgzNDQwNjAyCDgzNDQwNzAxCDgzNDQwNzAyCDgzMzMwNzAxCDgzMzMwNzAyCDgzNDYwNzAxCDgzNDYwNzAyCDgzNDcwNzAxCDgzNDcwNzAyCDgzMDcwNTAxCDgzMDcwNTAyCDgzMDcwNzAxCDgzMDcwNzAyCDgzMTAwNTAxCDgzMTAwNTAyCDgzMTAwNjAxCDgzMTAwNjAyCDgzMTAwNzAxCDgzMTAwNzAyCDIzNDUwOTAxCDIzNDUwOTAyCDIzNDAwODAzCDIzOTMwODAxCDIzOTMwODAyCDIzMzkxMDAxCDIzMzkxMDAyCDIzNTAxMDAxCDIzNDExMDAxCDIzMDExMDAxCDIzMDExMDAyCDIzMDExMDAzCDIzMTYxMDAxCDIzMjExMDAxCDIzNDAxMDAxCDIzMDUxMDAxCDIzMDUxMDAyCDIzMjExMTAyCDIzNDcxMTAxCDIzNDcxMTAyCDIzMjUxMTAxCDIzMDkxMTAxCDIzMDkxMTAyCDIzMDcxMTAxCDIzMTQxMTAxCDIzMzUxMTAxCDIzMTAxMTAxCDIzMTAxMTAyCDIzNjAxMTAxCDIzMzMxMTAxCDIzMzMxMTAyCDIzMzYxMTAxCDgzMzkxMTAxCDgzMjgxMTAxCDgzMzAxMTAxCDgzMTIxMTAxCDgzMDgxMTAxCDgzMzIxMTAxCDgzMzExMTAxCDgzMjIxMTAxCDgzNDQxMTAxCDgzNDcxMTAxCDgzMDcxMTAxCDgzMTAxMTAxCDgzMzMxMTAxCDIzMzUxMTAyCDIzMzQxMTAyCDIzMzYxMTAyCDIzMjgxMTAyCDIzMTYxMTAyCDIzNDUxMTAyCDIzNDAxMTAyCDIzMDgxMTAyCDIzMDAxMTAxCDIzMzIwNzAxCDIzMzEwNzAyCDIzMDAwNzAxCDIzMzMwNzAxCDIzMzQwNzAxCDIzNDYwNzAyCDIzMDkwNzAxCDIzMzAwNjA1CDIzMDAwODAyCDIzMDEwODAxCDIzMDEwODAzCDIzMDUwODAyCDIzMDcwODAyCDIzMDkwODAxCDIzMTAwODAyCDIzMTIwODAxCDIzMTIwODAzCDIzMTYwODAxCDIzMjEwODAyCDIzMjMwODAxCDIzMDEwOTAzCDIzMDgwOTAyCDIzMDUwOTAzCDIzMzkwOTA0CDIzNDEwOTAyCDIzNDAwOTA0CDIzMjEwOTAzCDIzMDgwOTAzCDIzMzEwOTAyCDIzMjIwOTAzCDIzNDQwOTAzCDIzMzMwOTAzCDIzMzQwOTAzCDIzNDYwOTAzCDIzNDcwOTAzCDIzMTAwOTAzCDIzMzYwOTAzCDAwMDEwMDAxCDAwMDEwMDAyCDgzMTYxMTAxCDgzMjMxMTAxCDIzNDAxMjAyCDIzMjExMjAxCDIzMjExMjAyCDIzMDUxMjAyCDIzMDUxMjAxCDIzMjgxMjAxCDIzNjUxMjAyCDIzNDcxMjAyCDIzNDcxMjAxCDIzMDkxMjAyCDIzMDkxMjAxCDIzMjUxMjAxCDgzNDYxMTAxCDIzMTQxMjAxCDgzMzkxMjAxCDIzMzUxMjAxCDIzMzcxMjAxCDIzMTAxMjAyCDIzMTAxMjAxCDIzMTExMjAyCDIzMTExMjAxCDIzNjAxMjAxCDgzMTYxMjAxCDgzMjgxMjAxCDIzMzYxMjAxCDgzMzAxMjAxCDIzMzkxMjAyCDIzMzkxMjAxCDIzNTAxMjAxCDIzNDExMjAxCDgzMTIxMjAxCDIzMDExMjAyCDIzMDExMjAxCDIzMTYxMjAxCDIzMTYxMjAyCDIzNDAxMjAxCDIzMDcxMjAxCDIzMDcxMjAyCDIzMjgxMjAyCDIzOTYxMjAxCDIzOTcxMjAxCDIzMzQxMjAyCDIzNDYxMjAyCDIzNDYxMjAxCDIzNjUxMjAxCDgzMDgxMjAxCDgzMzIxMjAxCDgzMzExMjAxCDgzMjMxMjAxCDgzMjIxMjAxCDgzNDQxMjAxCDIzNDExMDAyCDIzNDAxMDAzCDIzMzYxMDAyCDIzMjExMDAyCDIzMDUxMDAzCDIzMzQxMDAzCDIzMDgxMDAyCDIzNDQxMDAzCDIzNDYxMDAzCDIzMzkxMDAzCDIzMTIxMDA2CDIzMTIxMDA3CDIzMzAxMDAzCDIzNDcxMDAzCDIzMzMxMDAzCDIzMzExMDAzCDIzMjIxMDAzCDIzMTAxMDAzCDgzMTExMjAxCDgzNDYxMjAxCDgzNjUxMjAxCDgzNDcxMjAxCDgzMDcxMjAxCDgzMTAxMjAxCDgzMzMxMjAxCDAwMDExMjAxCDAwMDExMjAyCDIzMDUxMzAyCDgzMTExMTAxCDIzMzAxMjAyCDIzMzAxMjAxCDIzMTIxMjA1CDIzMTIxMjA0CDIzMTIxMjAzCDIzMjgxMzAxCDIzMjIxMjAxCDIzMjgxMzAyCDIzMjMxMjAxCDIzNDQxMjAyCDIzNDQxMjAxCDIzMTAxMzAyCDIzNTkxMjAxCDIzMDAxMjA0CDIzMDAxMjAzCDIzMDAxMjAyCDIzMDAxMjAxCDIzMzMxMjAyCDIzMzMxMjAxCDIzMzQxMjAxCDIzNjExMzAxCDIzNjExMzAyCDIzNjAxMzAxCDIzMzcxMzAxCDIzMTIxMjAyCDIzMTIxMjAxCDIzMDgxMjAxCDIzMDgxMjAyCDIzNDUxMjAxCDIzNDUxMjAyCDIzMzIxMjAyCDIzMzIxMjAxCDIzMzExMjAyCDIzMzExMjAxCDIzNzAxMzAxCDIzNzExMzAxCDIzMDIxMzAyCDAwMDExMzAxCDIzMzAxMzAxCDIzMzAxMzAyCDIzMTIxMzAyCDIzMTIxMzAzCDIzMzkxMjAzCDAwMDExMzAyCDIzMzYxMzAxCDIzMzYxMzAyCDIzNTAxMzAyCDIzNjAxMzAyCDIzMjIxMzAyCDIzNDAxMjAzCDIzMjExMjAzCDIzMDUxMjAzCDIzMzAxMjAzCDIzMTIxMjA3CDIzMDgxMjAzCDIzMzAxMzAzCDIzMTIxMzAxCDIzMzExMjAzCDIzNDQxMjAzCDIzMzMxMjAzCDIzMzQxMjAzCDIzNDcxMjAzCDIzMzkxMTAzCDIzNDExMTAyCDIzNDAxMTAzCDIzMjExMTAzCDIzMDUxMTAzCDIzMzAxMTAzCDIzMzYxMjAyCDIzMDgxMzAxCDIzMDgxMzAyCDIzNjkxMzAxCDIzNjkxMzAyCDIzNjkxMzAzCDIzMTIxMTA2CDIzMDgxMTAzCDIzMzExMTAzCDIzMDIxMzAxCDIzMjIxMzAxCDIzNDQxMzAxCDIzMjIxMTAzCDIzNTkxMzAxCDIzMDAxMzAxCDIzMDAxMzAyCDIzMDAxMzAzCDIzMDAxMzA0CDIzMzMxMzAxCDIzMDAxNDAyCDIzNjUxMzAyCDIzMzQxMzAyCDIzMzMxMzAyCDIzNjgxMzAxCDIzMzQxMzAxCDIzNDYxMzAxCDIzNDcxMzAyCDIzNjUxNDAyCDIzNjUxMzAxCDIzNDcxMzAxCDIzMDkxMzAxCDIzMjUxMzAxCDIzNjUxNDAxCDIzNDQxMTAzCDIzMzMxMTAzCDIzMzQxMTAzCDIzNDYxMTAzCDIzNDcxMTAzCDIzMTAxMTAzCDIzMzYxMTAzCDIzNjYxMzAxCDIzNjYxMzAyCDIzMzkxMzAxCDIzMzkxMzAyCDIzMzkxMzAzCDIzNTAxMzAxCDIzNDExMzAxCDIzNDcxNDAyCDIzMDExMzAxCDIzMDExMzAyCDIzNjcxMzAxCDIzNjcxMzAyCDIzNzIxMzAxCDIzNzIxMzAyCDIzMjExMzAxCDIzMjExMzAyCDIzMDUxMzAxCDIzMDcxMzAxCDIzNDcxNDAxCDIzMTQxMzAxCDIzMzUxMzAxCDIzMDkxNDAxCDIzMTAxMzAxCDIzMDcxNDAxCDIzMTQxNDAxCDIzMzUxNDAxCDIzMTAxNDAyCDAwMDExNDAxCDAwMDExNDAyCDgzMzkxMzAxCDgzNjcxMzAxCDgzMjgxMzAxCDgzMzAxMzAxCDgzMTIxMzAxCDgzMDgxMzAxCDgzMDIxMzAxCDgzMjIxMzAxCDgzNDQxMzAxCDgzMzMxMzAxCDgzNDYxMzAxCDgzNjUxMzAxCDgzNDcxMzAxCDgzMDcxMzAxCDgzMTAxMzAxCDgzMTExMzAxCDgzNjkxMzAxCDgzMzkxNDAxCDgzNjcxNDAxCDgzMjgxNDAxCDgzMzAxNDAxCDgzMTIxNDAxCDgzMDgxNDAxCDgzMDIxNDAxCDgzMjIxNDAxCDgzNDQxNDAxCDIzOTcxMTAxCDIzMzkxNDAyCDIzOTYxMTAxCDIzMzkxNDAzCDIzMzkxNDA0CDIzMDUxMzAzCDIzNDExNDAxCDIzMTAxNDAxCDIzMzcxNDAxCDIzMzYxNDAxCDIzMzQxMzAzCDgzMzMxNDAxCDgzNDYxNDAxCDgzNjUxNDAxCDgzNDcxNDAxCDgzMDcxNDAxCDgzMTAxNDAxCDIzNzQxNDAxCDIzNzQxNDAyCDIzMzkxNDAxCDIzNTAxNDAxCDIzMDIxMzAzCDIzMDExNDAxCDIzMDExNDAyCDIzNjcxNDAxCDIzMzkxMzA0CDIzNzIxNDAxCDIzNzIxNDAyCDIzMTIxMzA0CDIzMjExNDAxCDIzMDgxMzAzCDIzMDUxNDAyCDIzMDUxNDAxCDIzMjgxNDAxCDIzMjgxNDAyCDIzNzExNDAxCDIzMzAxNDAxCDIzMzAxNDAyCDIzNDQxMzAyCDIzMTIxNDAyCDIzMTIxNDAzCDIzMTIxNDAxCDIzMTIxNDA0CDIzMDgxNDAxCDIzMDgxNDAyCDIzNjkxNDAxCDIzNjkxNDAyCDIzNjkxNDAzCDIzMDIxNDAyCDIzMDIxNDAxCDIzMzAxMzA0CDIzMjIxNDAxCDIzNDQxNDAxCDIzNDQxNDAyCDIzMDAxNDAxCDIzMDAxNDAzCDIzMDAxNDA0CDIzMzMxNDAxCDIzMzMxNDAyCDIzNjgxNDAxCDIzNjgxNDAyCDIzMzQxNDAyCDIzMzQxNDAxCDIzNDYxNDAxCDIzNDYxNDAyCDgzNjkxNDAxCDIzNjkxMzA0CDIzMzMxMzAzCDIzNDcxMzAzCDIzNzIxMzAzCDIzMzYxMzAzCDIzNzQxNTAyCDIzNzQxNTAxCDIzMzkxNTAyCDIzMzkxNTAzCDIzMzkxNTAxCDIzMzkxNTA0CDIzNTAxNTAxCDIzNDExNTAxCDIzMDExNTAyCDIzMDExNTAxCDIzNjcxNTAxCDIzNzIxNTAxCDIzNzIxNTAyCDIzMjExNTAxCDIzNDAxMDAyCDIzNDgxMDAyCDIzMzQxMDAyCDIzMTIxMjA2CDIzMDUxNTAyCDIzMDUxNTAxCDIzMjgxNTAyCDIzMjgxNTAxCDIzNzExNTAxCDIzMzAxNTAxCDIzMzAxNTAyCDIzMTIxNTA0CDIzMTIxNTAyCDIzMTIxNTAzCDIzMTIxNTAxCDIzMDgxNTAxCDIzMDgxNTAyCDIzNjkxNTAxCDgzMzkxNTAxCDIzNjkxNTAyCDIzMDIxNTAyCDIzMDIxNTAxCDIzMjIxNTAxCDIzNDQxNTAyCDIzNDQxNTAxCDIzMDAxNTAyCDIzMDAxNTAxCDIzMzMxNTAxCDIzMzMxNTAyCDIzNjgxNTAxCDIzNjgxNTAyCDIzMzQxNTAyCDIzMzQxNTAxCDIzNDYxNTAyCDIzNDYxNTAxCDIzNjUxNTAxCDIzNDcxNTAyCDIzNDcxNTAxCDIzMDkxNTAxCDIzMDcxNTAxCDIzMTQxNTAxCDIzMzUxNTAxCDIzMTAxNTAxCDIzMTAxNTAyCDIzMzcxNTAxCDIzMzYxNTAxCDAwMDExNTAyCDAwMDExNTAxCDIzNzUxNTAxCDIzNzYxNTAxCDIzMzYxNTAyCDgzMzkxNTAyCDgzMjgxNTAxCDgzMzAxNTAxCDgzMTIxNTAxCDgzMTIxNTAyCDgzMDgxNTAxCDgzNjkxNTAxCDgzMDIxNTAxCDgzMjIxNTAxCDgzMjIxNTAyCDgzNDQxNTAxCDgzMzMxNTAxCDgzNDYxNTAxCDgzNjUxNTAxCDgzNDcxNTAxCDgzMDcxNTAxCDgzMTAxNTAxCDgzMTAxNTAyCDgzMTAxNDAyCDgzMzkxNDAyCDgzMTIxNDAyCDIzMjMwNjAyCDIzMDAwNjAxCDIzMDAwNjAyCDIzMDAwNjAzCDIzMzMwNjAxCDIzMzMwNjAyCDIzOTEwNjAxCDIzOTEwNjAyCDIzNDcwNjAxCDIzNDcwNjAyCDIzMDkwNjAxCDIzMDkwNjAyCDIzMjUwNjAxCDIzMzUwNjAxCDIzMzUwNjAyCDIzMTAwNjAxCDIzMTAwNjAyCDIzMTEwNjAxCDIzMTEwNjAyCDIzMTEwNjAzCDIzMzYwNjAxCDIzMjUwODAxCDIzMzAwOTA0CDIzMTIwOTA2CDIzMjYwODAxCDIzMjgwODAxCDIzMzAwODAxCDIzMzAwODAyCDIzMzEwODAxCDIzMzEwODAyCDIzMzIwODAxCDIzMzMwODAxCDIzMzMwODAyCDIzMzQwODAxCDIzMzQwODAyCDIzMzUwODAxCDIzMzYwODAxCDIzMzYwODAyCDIzMzcwODAxCDIzMzkwODAxCDIzMzkwODAyCDIzNDAwODAxCDIzNDAwODAyCDIzNDEwODAxCDIzNDQwODAxCDIzNDQwODAyCDIzNDYwODAxCDIzNDYwODAyCDIzNDcwODAxCDIzNDcwODAyCDIzNTAwODAxCDIzNTgwODAxCDIzNTgwODAyCDIzNDAwNzAzCDIzMDAwODA1CDIzMzkwOTAxCDIzMzkwOTAyCDIzMzkwOTAzCDIzNTAwOTAxCDIzNDEwOTAxCDIzMDEwOTAxCDIzMDEwOTAyCDIzMDEwOTA0CDIzMTYwOTAxCDIzNDAwOTAxCDIzNDAwOTAyCDIzMjEwOTAxCDIzMjEwOTAyCDIzMDUwOTAxCDIzMDUwOTAyCDIzMjgwOTAxCDIzMjgwOTAyCDIzMzAwOTAxCDIzMzAwOTAyCDIzMzAwOTAzCDIzMTIwOTAxCDIzMTIwOTAyCDIzMTIwOTAzCDIzMTIwOTA0CDIzMTIwOTA1CDIzMDgwOTAxCDIzMzIwOTAxCDIzMzEwOTAxCDIzMjMwOTAxCDIzMjMwOTAyCDIzMjIwOTAxCDIzMjIwOTAyCDIzNTgwOTAxCDIzNTgwOTAyCDIzNDQwOTAxCDIzNDQwOTAyCDIzMDAwOTAxCDIzMDAwOTAyCDIzMDAwOTAzCDIzMDAwOTA0CDIzMDAwOTA1CDIzMDAwOTA2CDIzMzMwOTAxCDIzMDgwODAzCDIzMjIwODAzCDIzNDQwODAzCDIzMzMwODAzCDIzMzQwODAzCDIzNDYwODAzCDIzNDcwODAzCDIzMTAwODAzCDIzMzYwODAzCDgzMzkxMDAxCDgzMjgxMDAxCDgzMzAxMDAxCDgzMTIxMDAxCDgzMDgxMDAxCDgzMzIxMDAxCDgzMzExMDAxCDgzMjIxMDAxCDgzNDQxMDAxCDgzNDYxMDAxCDgzNDcxMDAxCDgzMDcxMDAxCDgzMTAxMDAxCDgzMzMxMDAxCDIzNDAwOTAzCDIzMzkxMTAxCDIzMzkxMTAyCDIzNTAxMTAxCDIzNDExMTAxCDIzMDExMTAxCDIzMDExMTAyCDIzMDExMTAzCDIzMTYxMTAxCDIzMjExMTAxCDIzNDAxMTAxCDIzMDUxMTAxCDIzMDUxMTAyCDIzNTkxMTAxCDIzMjgxMTAxCDIzNDUxMTAxCDIzMzAxMTAxCDIzMzAxMTAyCDIzMzcxMTAxCDIzMTIxMTAxCDIzMTIxMTAyCDIzMTIxMTAzCDIzMTIxMTA0CDIzMTIxMTA1CDIzMDgxMTAxCDIzMzIxMTAxCDIzMzIxMTAyCDIzMzExMTAxCDIzMzExMTAyCDIzMjIxMTAxCDIzMjIxMTAyCDIzNDQxMTAxCDIzNDQxMTAyCDIzMjMxMTAxCDIzMjMxMTAyCDIzMTExMTAxCDIzMTExMTAyCDIzMDAxMTAyCDIzMDAxMTAzCDIzMDAxMTA0CDIzMzQxMTAxCDIzNDYxMTAxCDIzNDYxMTAyASAUKwOFCGdnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZ2dnZxYBAqoEZAIFD2QWAmYPEA8WAh8AZGQQFQ0JMjAwNC0yMDA1CTIwMDUtMjAwNgkyMDA2LTIwMDcJMjAwNy0yMDA4CTIwMDgtMjAwOQkyMDA5LTIwMTAJMjAxMC0yMDExCTIwMTEtMjAxMgkyMDEyLTIwMTMJMjAxMy0yMDE0CTIwMTQtMjAxNQkyMDE1LTIwMTYBIBUNCTIwMDQtMjAwNQkyMDA1LTIwMDYJMjAwNi0yMDA3CTIwMDctMjAwOAkyMDA4LTIwMDkJMjAwOS0yMDEwCTIwMTAtMjAxMQkyMDExLTIwMTIJMjAxMi0yMDEzCTIwMTMtMjAxNAkyMDE0LTIwMTUJMjAxNS0yMDE2ASAUKwMNZ2dnZ2dnZ2dnZ2dnZ2RkAgcPZBYCZg8QDxYCHwBkZBAVAwExATIBIBUDATEBMgEgFCsDA2dnZ2RkAg8PZBYMAgEPZBYOAgEPFgIeCWlubmVyaHRtbAUGJm5ic3A7ZAICDxYCHwEFBiZuYnNwO2QCAw8WAh8BBQYmbmJzcDtkAgQPFgIfAQUGJm5ic3A7ZAIFDxYCHwEFBiZuYnNwO2QCBg8WAh8BBQYmbmJzcDtkAgcPFgIfAQUGJm5ic3A7ZAICD2QWDgIBDxYCHwEFBiZuYnNwO2QCAg8WAh8BBQYmbmJzcDtkAgMPFgIfAQUGJm5ic3A7ZAIEDxYCHwEFBiZuYnNwO2QCBQ8WAh8BBQYmbmJzcDtkAgYPFgIfAQUGJm5ic3A7ZAIHDxYCHwEFBiZuYnNwO2QCAw9kFg4CAQ8WAh8BBQYmbmJzcDtkAgIPFgIfAQUGJm5ic3A7ZAIDDxYCHwEFBiZuYnNwO2QCBA8WAh8BBQYmbmJzcDtkAgUPFgIfAQUGJm5ic3A7ZAIGDxYCHwEFBiZuYnNwO2QCBw8WAh8BBQYmbmJzcDtkAgQPZBYOAgEPFgIfAQUGJm5ic3A7ZAICDxYCHwEFBiZuYnNwO2QCAw8WAh8BBQYmbmJzcDtkAgQPFgIfAQUGJm5ic3A7ZAIFDxYCHwEFBiZuYnNwO2QCBg8WAh8BBQYmbmJzcDtkAgcPFgIfAQUGJm5ic3A7ZAIFD2QWDgIBDxYCHwEFBiZuYnNwO2QCAg8WAh8BBQYmbmJzcDtkAgMPFgIfAQUGJm5ic3A7ZAIEDxYCHwEFBiZuYnNwO2QCBQ8WAh8BBQYmbmJzcDtkAgYPFgIfAQUGJm5ic3A7ZAIHDxYCHwEFBiZuYnNwO2QCBg9kFg4CAQ8WAh8BBQYmbmJzcDtkAgIPFgIfAQUGJm5ic3A7ZAIDDxYCHwEFBiZuYnNwO2QCBA8WAh8BBQYmbmJzcDtkAgUPFgIfAQUGJm5ic3A7ZAIGDxYCHwEFBiZuYnNwO2QCBw8WAh8BBQYmbmJzcDtkZOJLvl0BTYOnC03e70WDDZp7xspW");
		map.put("__EVENTVALIDATION", "/wEW1AgC6M320g0C5Mabig0C9Kmx5AEC9Kn95wEC9Kn55wEC9KnF5wEC9KnB5wEC9KnN5wEC9KnJ5wEC9KnV5wEC9KmR5AEC9Kmd5AEC66nx5wEC66n95wEC66nF5wEC66nB5wEC66nN5wEC66nV5wEC66mR5AEC66md5AEC6qnx5wEC6qn95wEC6qn55wEC6qnF5wEC6qnN5wEC6qnJ5wEC6qnV5wEC76n95wEC76n55wEC76nF5wEC76nB5wEC76nN5wEC76nJ5wEC76nV5wEC76mR5AEC76md5AEC/Knx5wEC/Kn95wEC/Kn55wEC86md5AEC5Kmx5AECjrrczwECjtX2oQ0C2dnD5gYC8feq2QIC8fe+/AsC8ffSkAMC8ffmtwgC8feWgg0C8feC7wUC8feuhgMC8fea4wsCms6o+gwCms6UpwcCms6AgA4Cms7s7QYCms7Y1gECms7EswgC2bbpiAoC4caTjA0Ck++jwgMCk+//0wUCoIHLqwQC1qGbrQUCnc+P9QUCnc/z6wMCnc/7OwLnrNDzBwLnrMTWDgLnrPi5AQLnrMy7AgLnrOCeBQKq4buiBwKdz+f0BAKdz5vYDwKdz/O0BwKdz4/GCQKggYOHCAKggbdqAtahi4gIAtahz/4HAqCBx8YLAqCB02MC56y8swYC56z43AgCquGbnggCquHfjAYCquHz1w4CquG3xgQCquGrqQ8CquHvnwUCnc/f9AcC1qHjjwsC1qGX0wMCoIHThgoC1qGnzwoC1qGz5AMCoIG/xgoCquH/4QYCquG78wgCquHH3AQC56yI8wYCnc+DtAEC56z48wQC56y84gICzMGK8gwCnc+rtAYCnc+30Q8Cnc+39AYC2aHb2QMC2aH3sAoCo4GXjQoCreGXiwcCreHTlAkCnM/HzgoC5qzAngUCxsqf2QICku/L/goC2aHn2QMC2aGryAkC5qzs8gEC2aGr/wUC2aHniA4Co4HX0AICo4GbxwgCreHX7g8CreGb3QUCo4G7mgICo4H3qwQCnM+TzwoCnM//6wMCnM+79QUC2aGDyAgC5qzw1g4C5qzc8wcCreHrkA0CreGnogcC2aG32Q0C2aH7zwsCnM+T9QQCnM//tAcCo4GjagKjgY+HCAKjgd9jAqOB88YLAtmh+/4HAtmht4gIApzP17QGApzPj+sNApzPy/QHAtmhg9MDAtmh748LAtmhv+QDAtmh088KAq3h6+EGAqOB59cMAqOBq8YKAq3h3/kNAuastPMGApzPj7QBAqOB34YKAuas5PMEApzPo/QGAq3hv/MIAqOBo8YKAqOB/9cMAq3hy9wEAq3h1/kNAuasjPMGApzPh7QBApzPw8ULAqOB14YKAuas/PMEAuasoOICAuasoLMGAuas/NwIApzPu/QGApzPr98JAq3ho4sHAq3h/5QJAuas5LkBAq3hn/QFAq3hw+oDApzPo84EAuas3MUFAuasgLQDAqOBl8cIAu7X1s0JAuasqOICAu7Xjs0IAu7X8qMGAuas6PIBAtmh44gOAtmhp/8FApLvx/4KAq3h0+4PAu7Xmo0LAu7X5ikCo4G36wcCnM+39QUCnM/76wMCnM/vzgoC5qzY8wcC5qzM1g4CreGjogcCreHnkA0C7tfyjAoC7teOngwC7tf+zQ4CnM/7tAcCo4GLhwgCo4G/agLZobOICALZoff+BwKjgc/GCwKcz9PfCQKt4dv5DQKt4ZfdBQKjgePXDAKt4c/cBALZoaPICQLZof/ZAwLmrOTyAQLmrJjWCALZof+IDgLZoaP/BQKcz9c9ApzPy4ALApLvw/4KApLvh20Co4GTxwgCo4Gv0AICreGT3QUCreGv7g8C7teWjQsC7tfiKQLu187GCQKjgc+rBAKjgbOaAgKcz7P1BQKcz/frAwKcz+vOCgLmrNTzBwLmrMjWDgLmrPy5AQLmrPC7AgLu19LNCQLu18YQAq3hv6IHAq3h45ANApzPn9gPApzP97QHAqOBh4cIAqOBu2oCo4HLxgsCo4HXYwLZoY+ICALZofP+BwKt4cOMBgKt4ffXDgKcz7vRDwKcz4frDQLZoeePCwLZoavPCgLZobfkAwKt4afzCAKt4fPcBALmrMj5AQKcz8ciApzP+4ULAq3h+5QJAq3hv4sHApzP0z0CreGPKAKcz4uOBwKjgdPNCwKt4Zv0BQKt4d/qAwLmrNjFBQLmrJy0AwLmrOC5AQLmrPS7AgKt4fudCAKt4dPXDgKt4ZfGBAKt4fvuDQKt4eOzAQKt4c/cBQKt4afcBAKt4ZuiBwKt4d+QDQLmrNjzBALmrJyzBgLmrNjcCALmrKTWDgLmrKy7AgLmrOjyBgKjgc/GCAKjgeOGCAKjgZdqAqOBs2MCnM+T0Q8CnM+79AcCnM//6g0C2aHfjwsC2aHz0gMC2aGDzwoC2aHv6wMCo4GbxgoCreHb4QYCreGj3AQC5qzk8gYCnM//uwECnM/XOwKjgY+GCgLmrJizBgLmrNTcCALmrNTzBALmrJjiAgKcz5P0BgKcz4ffCQLZocv2CALZoZuxCgKjgbuNCgKt4buLBwLmrOSeBQKt4Zf0BQKjga/NCwLZoefBDgKcz7vOBALZoY+2CgLZoYOBCwLmrNTFBQKcz8MiAoOv548IApzPrz0C5qyoswYC5qzk3AgCxsrz2AICxsrv9AUCxsqP6gQCxsrT6wMC0Kqw8wcC0Kqk1g4Cl++bogcCl+/fkA0Cg6/rjwgCg6+v/gcCg6+r/gcCg6+HzwoCg6+T5AMC0KrY8wQC0Kqc4gICl++z+Q0CjY/vmQICxsrH9AQCxsr73w8CjY+rqwQCxsrP2AICxsqL6gQCjY+nqwQCjY/rmQICxsrr9AUCxsqv6wMCl++XogcC0KqM8wcC0Kqg1g4Cl+/bkA0CxsrD9AQCxsr33w8CxsqLtAYCxsqX0Q8CxsqHtAYCxsqT0Q8Cg6/DjwsCl++n3AQCg6/30gMCl++j3AQCl++P+Q0C0KrU8wQC0KqY4gICg6+DzwoCg6/v6wMCg6/fjwsCg6/z0gMCl+/P3AQCl+/b+Q0CjY/3qwQCjY+7mgICjY/zqwQCjY+3mgICjY/PqwQCjY+zmgICxsq79QUCxsr/6wMCxsq39QUCxsr76wMCxsqz9QUCxsr36wMC0KrU8wcC0KrI1g4Cl++nogcCl+/rkA0Cl++jogcCl+/nkA0Cl++/ogcCl+/jkA0Cg6+3iAgCg6/7/gcCg6+ziAgCg6/3/gcCg6+PiAgCg6/z/gcCxsqvtAYCxsq70Q8Cg6/njwsCg6+b0wMCg6+rzwoCg6+35AMCl+/z3AQCl+/f+Q0Cl+/L3AQCl+/X+Q0C0Krk8wQC0Kqo4gIC0Krg8wQC0Kqk4gIC0Kr88wQC0Kqg4gIC2aGrzwsC2aHn2A0C2aGzwgwC7tfyjAsC7tfeKQKdz5PZAgKdz6/qBAKT79/+CgLWob/ICQKq4d/dCwKq4ZvvDQKq4eeLBQLnrODyAQKgge/GCALWofuIDgKq4e/cBQKq4avuDwKggafQAgLWoaPPCgLWoY/kAwKggbvGCgKq4fvhBgKq4bfzCAKq4cPcBALnrITzBgKdz5+0AQLnrPTzBALnrLjiAgLMwYbyDAKdz6e0BgKdz7PRDwKdz7P0BgLHyu/YAgKKj8erBALHyov1BQLRqqzzBwKU77eiBwLHyuP0BALHys+0BwKKj5+HCAKAr4eICAKAr6PPCgKU78PcBALRqvTzBALHyqe0BgKdz9vFCwKdz5/rDQKdz6ffCQKggYuaAgLnrJDWCALWoYfZDQLWobv/BQKq4fuQDQKq4ZeeCAKcz+v0BAKcz7PGCQKt4Z+eCAKcz6+0BgKcz8P0BwLZoZvTAwKt4ePhBgKcz8eACwKt4b+MBgKt4b/dCwKt4ceLBQKt4YvuDwKt4bP5DQKt4d/hBgLmrJziAgLmrLDzBwLmrNi5AQLmrMDyAQKjgYvQAgKjgafGCwKt4cOLBQKt4duQDQKt4ZOLBwKcz7PPCALZodfZAwLZofOwCgKjgZONCgKt4c/7BQKcz+vFCQKjgYfNCwLZod/BDgKcz/+NBwKcz5POBALZoee1CgLZofuACwLmrIzFBQKcz7siAu/uy9oLAu/uh+QNAtGq/PIBAoqPw8YLAtaht/8FAqCB58YIAqCBo9ACAqrho+4PAqrh59wFAqCBw6sEAszB0sICAtahi+QDAtahv88KAqrhs/MIAqrh9+EGAqCBt8YKAoCv/48LAuesgPMGAsfK69gCAp3Pm7QBAp3P8zsC56y04gIC56zw8wQC56zw3AgC56y0swYCzMGC8gwC0ar48gECio/DqwQCnc+P9AYCx8qH9QUCnc+n6gQCnc/r2AICk+/X/goC1qG3yAkC0aqo8wcCquGT7w0CquHX3QsC56z48gEC56zs1QgC1qHziA4CquHf3AQCquGr+Q0CoIGHmgIC79f2zAsC79e6jAUCnc+b6w0C1qHv0gMC1qH7jwsCzMGWsQgClO+zogcCx8r/9AQCx8rLtAcCio/fxgsCio+bhwgCgK+DiAgC1qH72QMC1qHTwgwCnc+r3wkCoIGr0AICquG3iwcCnc+3zgQCquH/kA0C1qHjwQ4C1qGLtgoCnc+7hwwC56yU4g0C56yIxQQCnc/nzgoC1qGfgQsCnc+DjgcCnc+b4wYCoIGrzQsC56zQxQUC0aq0swYCgK/7jwsCts+WsQgCgK+/zwoClO/f3AQC0arw8wQCx8qjtAYC7O7D2gsC7O6f5A0CquG/7g8C0aq4swYCnc/L6wMCnc+H9QUC56z4ngUC56zEuwIC56zwuQECoIHfqwQCoIGbhwgCoIGDmgICoIHfxgsC1qHH/gcC1qGDiAgC56yw4gICk++7wgMCquGPxgQCquHL1w4CquHXjAYCquGTnggCnc+P0Q8Cnc+jtAYCnc/X9AcCzMHCsQ4CzMGeQwLMwZ7yDAKdz887Aues3NYOAuesqPMHAqrhs6IHAqrh95ANAtahx88LAtahg9kNAp3Pk9gPAp3P//QEAp3Ph8YJAp3Py7QHAomP4+cLAomPp6cFAqrh++ADAuzux9oLAp3Pg/UFAp3Px+sDAues2NYOAueszLkBAp3Ps4cMAuzug+QNAp3Pi/QGAp3Pv98JApPvl20CzMHC4AoCoIGLagLWoavCDAKggY+NCgKq4Y+LBwKdz//OCgLnrIDFBAKq4ev7BQKdz/vOCgLnrKTzBwKdz5PjBgLWofvBDgKdz5uOBwKdz4/OBALWoZeBCwKdz7eHDALWoffZAwLWoa/CDAKggbONCgKq4bOLBwKdz+POCgKdz6PfCQKq4Y+iBwKq4fOQDQLMweLVBQLMwb7nDwLMwYqcBwLnrJDiDQKq4e/7BQKdz5fjBgKq4cedCwKggZeHCALWoZ+ICAKggafNCwKT77fCAwKq4e+dCAKq4dOMBgKq4cfXDgKq4YvGBAKdz7+0BgKq4c+MBgLMwa7CAgKdz5frDQKdz4vRDwLMwb6WCgKdz9P0BwLWofePCwLWoYfkAwLMwcrCAgLMwZKxCALWobvPCgKq4fPhBgKggbPGCgLMwY6xCALWof/BDgKdz5+OBwKdz7POBALWoYe2CgLWoZuBCwLnrKzFBQKdz9siAszBhvEJAszBulQCnc/n2AICnc+j6gQCnc+PhwwCk+/T/goC1qGzyAkC1qGj5AMCquHT3QsCquHv7g0CzMHKsAsCzMHWbQKJj9vnCgKJj8/KDQKggePGCAKggb/QAgKq4ePcBQKq4dvcBALWodfPCgLnrJzzBgKdz5e0AQKq4e/hBgLnrMzzBAKq4ffcBALnrLjzBgKdz7O0AQLnrKziAgLs7tvaCwLs7pfkDQLHyufYAgK2z8qwCwKKj9+rBALHyoP1BQLRqqTzBwKU74+iBwKU78edCwKKj5eHCAKAr5+ICALHyr+0BgKAr/ePCwK2z5KxCAKAr7vPCgKU79vcBALRqszzBALRqrCzBgK2z+LVBQLHyoPZAgK2z+awCwKKj/urBALHyr/1BQLRqsDzBwKU76uiBwKU7+OdCwKKj7OHCAKAr7uICALv176MBQKdz9/qBALv1/rMCwKdz6uHDAKdz8fPCAKq4YuLBwLWoa/ICQLnrOjzBAKdz+s7Ap3Pp/QGAp3Pi84EAsfK27QGAoCvk4gLArbPjrEIAoCv188KApTv99wEAtGq6PMEAomPr+cFAomPk9YDAp3Pg9kCApPvz/4KAqrh78sKAqrhz90LAqrhi+8NAszB5rALAp3Pq88IAomP9+cKAomP68oNAueswLsCAqCBn8cIAqrh5/sFAqrh2+4PAqrhn90FAqCB+6sEAqCBv5oCAomPw6cFAp3Pv/UFAp3P4+sDAtahw/4HAues9NYOAues6LkBAueswPMHAues/LsCAqrhq6IHAqrh75ANAszBntYFAszB2ucPAszBppwHAqrhl+EDAqrh450LAp3Pvz0CoIGzhwgC1qG7iAgC1qH//gcCquGLnggCquHj1w4CquGnxgQCnc/btAYCnc+n0Q8CzMHalgoCzMGeBQKdz7PrDQKdz8/0BwLWoZOICwLWoYfTAwK2z57WBQLMwabEAwKdz5eOBwLWoZOBCwKJj+OtBAKdz9MiAomP79UDAomPq+cFAp3P2+oEAp3Pp4cMAp3Pn9kCAp3Pw88IApPvy/4KAtahq8gJAqrhh+8NAqrhy90LAszB4rALAomP8+cKAomP58oNAqCBm8cIAtahv/8FAtah34MDAp3Pg+sNAues7OENAqrh1+4PAqrhm90FAqCBu5oCAqCB96sEAomP36cFAp3Pu/UFAp3P/+sDAues+LsCAues8NYOAues5LkBAues3PMHAqrhp6IHAqrh65ANAszBmtYFAsfKn9kCAszB1ucPAqrhk+EDAqrh/50LAqCBj4cIAtah+/4HAtaht4gIAqrhy4wGAqrhh54IAp3P17QGAp3Po9EPAszB1pYKAszBmgUCnc+P6w0Cnc/L9AcC1qGD0wMC1qHvjwsCzMGKsQgC1qG/5AMC1qHTzwoCquHr4QYCquHz3AQC56y08wYCnc+PtAEC56zk8wQC56yo4gICnc/nOwKdz6P0BgLs7pvkDQLs7t/aCwKJj++mBwKJj4PnBAKdz9ffCQLHytvqBAKKj/erBALHyrv1BQLRqtzzBwLRqvDWDgKU76eiBwK2z5rWBQKU7/+dCwKKj4+HCAKKj6NqAoCvt4gIAsfK17QGAoCv748LArbPirEIAoCv088KApTv89wEAtGq5PMEAtGqqOICAtGqrOICAsfK3+oEAtGq9NYOAqOB22MCreGDnggCreHHjAYCreH71w4CnM/TtAYCnM+/0Q8C7teijQgC7tf+ngIC2aGvzwoC2aG75AMCreHn4QYCreGj8wgCo4GnxgoCnM+LtAECnM/HxQsC5qzg8wQC5qyk4gIC5qykswYC5qzg3AgC5qzM+QECnM+/9AYCo4GfxgoCnM+HPQLmrPDhDQKjgbOGCgKjgaurBAKcz+/0BQKcz9PrAwKcz9O0BwKcz+/FCQKcz8f0BAKcz4u0BgKcz5fRDwKcz7/0BwKcz+PqDQKcz+O7AQKcz5f0BgKcz4vfCQKcz9s7ApzP89gCApzPj+oEAtmh24gOAtmhn/8FAtmhn8gJAtmh648IAtmhr/4HAtmhw48LAtmh99IDAtmhh88KAtmhk+QDApLvv/4KApLv3wICku+D8Q8C2aHXwgwCreGLqQ8CnM/P2AICnM+L6gQCnM+XhwwCku+7/goC2aGbyAkCreG73QsCreH37g0CreH/swEC5qzc8gEC2aHXiA4C2aGb/wUCo4HLxggCo4GH0AICreHL3AUCreGH7g8Co4GnqwQCo4HrmQICnM/r9AUCnM+v6wMCnM/DzgoC5qyM8wcC5qyg1g4C5qzUuQEC5qyouwIC5qzcngUCreGXogcCnM/D9AQCnM+vtAcCo4GjxgsCo4GPYwKjgf+GCAKjgZNqApLv2wICku+f8Q8C2aHnjwgC2aGr/gcCreH3nQgCreG7jAYCreGv1w4CreGTxgQCreGHqQ8CreHLnwUCnM+HtAYCreHz+wUCo4GLzQsC2aHDwQ4CnM/jjQcCnM+XzgQC2aHrtQoC2aH/gAsC5qywxQUCnM+/IgLHypPZAgKKj8urBALHyo/1BQLRqtDzBwKU77uiBwLHyuf0BALHyvO0BwKKj4OHCAKAr4uICAKAr+OPCwKAr6fPCgKU78fcBALRqvjzBALHyqu0BgLZoY/CDAKdz+/YAgKdz6vqBAKT79v+CgLWobvICQKq4dvdCwKq4ZfvDQKq4eOLBQLnrPzyAQKggevGCALWofeIDgKq4evcBQKq4afuDwKT77/CAwKggcerBALWocvPCwKdz4v1BQKdz8/rAwKdz/c7AuesrPMHAueswNYOAues9LkBAuesyLsCAues/J4FAqrht6IHAp3P4/QEAp3Pl9gPAp3Pz7QHAp3Pi8YJAqCBn4cIAqCBs2oC1qGHiAgC1qHL/gcCoIHDxgsCoIGvYwLnrLizBgLnrPTcCAKq4duMBgKq4c/XDgKq4bPGBAKdz9v0BwLWof+PCwLWoZPTAwLhqbniAQK23ePZAQK33ffDDAK03YvZDgK93Z/DDQK63fO6DQK13ZuBAwLvn5zvBQLsn9iuAwLtn8TuAgLyn4AuAvOf7O4DAvCfqK4BAqGblcACAuadpcoEAuedpcoEAumdpcoEAoznisYGAqrH78cEAtXckYcIy63xWMrecCPotsLGitAq15fPaSE=");
		map.put("StudentJZ1$DropDownListXY", "52");
		map.put("StudentJZ1$DropDownListZYMC", "2344");
		map.put("StudentJZ1$DropDownListDQSZJ", "2012");
		map.put("StudentJZ1$DropDownListXZB", "12软件1");
		map.put("XN1$DropDownListXN", "2013-2014");
		map.put("XQ1$DropDownListXQ", "1");
		map.put("Button1", "查询");
		map.put("ButtonList", "班级列表模式");
		map.put("btnExport", "课表输出");
		List<NameValuePair> nvps = new ArrayList<NameValuePair>();
		for (Map.Entry<String, String> m : map.entrySet()) {
			nvps.add(new BasicNameValuePair(m.getKey(), m.getValue()));
		}
		
		
		CloseableHttpResponse response2 =null;
		try {
		HttpPost kbget = new HttpPost(BASEURL+"public/kebiaoall.aspx");
		kbget.setEntity(new UrlEncodedFormEntity(nvps, "UTF-8"));
			 response2 = httpclient.execute(kbget);
		} catch (ClientProtocolException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		
		return response2;
	}
	
}
